// Auto-generated by scripts/build.mjs — do not edit manually
// Built: 2026-06-24T01:37:09.232Z

window.__BUILD_TIMESTAMP = "2026-06-24T01:37:09.232Z";

window.__ROUTE_MAP = {
  "#aiml-ab-testing-experimentation": "content/aiml/ab-testing-experimentation.json",
  "#aiml-activation-functions": "content/aiml/activation-functions.json",
  "#aiml-ann-history": "content/aiml/ann-history.json",
  "#aiml-cv-deep-dive": "content/aiml/cv-deep-dive.json",
  "#aiml-llm-engineering": "content/aiml/llm-engineering.json",
  "#aiml-ml-behavioral": "content/aiml/ml-behavioral.json",
  "#aiml-ml-chestnut-questions": "content/aiml/ml-chestnut-questions.json",
  "#aiml-ml-coding-patterns": "content/aiml/ml-coding-patterns.json",
  "#aiml-ml-company-focus": "content/aiml/ml-company-focus.json",
  "#aiml-ml-data-centric": "content/aiml/ml-data-centric.json",
  "#aiml-ml-fundamentals": "content/aiml/ml-fundamentals.json",
  "#aiml-ml-gpu-deep-dive": "content/aiml/ml-gpu-deep-dive.json",
  "#aiml-ml-interpretability-fairness": "content/aiml/ml-interpretability-fairness.json",
  "#aiml-ml-leadership-strategy": "content/aiml/ml-leadership-strategy.json",
  "#aiml-ml-math": "content/aiml/ml-math.json",
  "#aiml-ml-mock-interviews": "content/aiml/ml-mock-interviews.json",
  "#aiml-ml-papers": "content/aiml/ml-papers.json",
  "#aiml-ml-production-ops": "content/aiml/ml-production-ops.json",
  "#aiml-ml-project-structure": "content/aiml/ml-project-structure.json",
  "#aiml-ml-roadmap": "content/aiml/ml-roadmap.json",
  "#aiml-ml-staff-system-design": "content/aiml/ml-staff-system-design.json",
  "#aiml-ml-system-design": "content/aiml/ml-system-design.json",
  "#aiml-ml-zero-to-hero": "content/aiml/ml-zero-to-hero.json",
  "#aiml-neural-network-training": "content/aiml/neural-network-training.json",
  "#aiml-nlp-deep-dive": "content/aiml/nlp-deep-dive.json",
  "#aiml-recommendation-systems": "content/aiml/recommendation-systems.json",
  "#aiml-rl-rlhf": "content/aiml/rl-rlhf.json",
  "#aiml-supervised-learning": "content/aiml/supervised-learning.json",
  "#aiml-types-of-anns": "content/aiml/types-of-anns.json",
  "#aiml-unsupervised-learning": "content/aiml/unsupervised-learning.json",
  "#api-design-staff": "content/sysdesign/api-design-staff.json",
  "#behavioral-staff": "content/patterns/behavioral-staff.json",
  "#career-staff": "content/patterns/career-staff.json",
  "#computer-networks": "content/networking/computer-networks.json",
  "#database-fundamentals": "content/databases/databases.json",
  "#databases-staff": "content/databases/databases-staff.json",
  "#distributed-systems-staff": "content/sysdesign/distributed-systems-staff.json",
  "#dsa-staff": "content/programming/dsa-staff.json",
  "#engineering-patterns-staff": "content/patterns/engineering-patterns-staff.json",
  "#faang-facts": "content/faang/faang-facts.json",
  "#genai-agent-advanced": "content/genai/agent-advanced.json",
  "#genai-alignment": "content/genai/alignment.json",
  "#genai-context-engineering": "content/genai/context-engineering.json",
  "#genai-finetuning": "content/genai/fine-tuning.json",
  "#genai-harness-engineering": "content/genai/harness-engineering.json",
  "#genai-kvcache": "content/genai/kv-cache.json",
  "#genai-llm-serving": "content/genai/llm-serving.json",
  "#genai-loop-engineering": "content/genai/loop-engineering.json",
  "#genai-mcp": "content/genai/mcp.json",
  "#genai-moe": "content/genai/mixture-of-experts.json",
  "#genai-multimodal": "content/genai/multimodal.json",
  "#genai-observability": "content/genai/observability.json",
  "#genai-pretraining": "content/genai/pretraining.json",
  "#genai-prompt-engineering": "content/genai/prompt-engineering.json",
  "#genai-rag": "content/genai/rag.json",
  "#genai-security": "content/genai/security.json",
  "#genai-skills": "content/genai/skills.json",
  "#genai-synthetic-data": "content/genai/synthetic-data.json",
  "#genai-tools": "content/genai/tools.json",
  "#genai-transformer-architecture": "content/genai/transformer-architecture.json",
  "#genai-what-is-llm": "content/genai/what-is-llm.json",
  "#oop-staff": "content/oop/oop-staff.json",
  "#operating-systems": "content/os/operating-systems.json",
  "#product-sense-staff": "content/product/product-sense-staff.json",
  "#py-algorithms": "content/python/basics/algorithms.json",
  "#py-basics-api": "content/python/basics/api.json",
  "#py-basics-concurrency": "content/python/basics/concurrency.json",
  "#py-basics-datatypes": "content/python/basics/datatypes.json",
  "#py-basics-files": "content/python/basics/files.json",
  "#py-basics-io": "content/python/basics/io.json",
  "#py-basics-loops": "content/python/basics/loops.json",
  "#py-complexity": "content/python/basics/complexity.json",
  "#py-design-docs": "content/python/basics/design-docs.json",
  "#py-ds-builtins": "content/python/basics/ds-builtins.json",
  "#py-ds-graph": "content/python/basics/ds-graph.json",
  "#py-ds-heap": "content/python/basics/ds-heap.json",
  "#py-ds-linkedlist": "content/python/basics/ds-linkedlist.json",
  "#py-ds-stackqueue": "content/python/basics/ds-stackqueue.json",
  "#py-ds-tree": "content/python/basics/ds-tree.json",
  "#py-exceptions": "content/python/basics/exceptions.json",
  "#py-functional": "content/python/basics/functional.json",
  "#py-google-culture": "content/python/basics/google-culture.json",
  "#py-logging": "content/python/basics/logging.json",
  "#py-memory": "content/python/basics/memory.json",
  "#py-modules": "content/python/basics/modules.json",
  "#py-oop": "content/python/basics/oop.json",
  "#py-performance": "content/python/basics/performance.json",
  "#py-security": "content/python/basics/security.json",
  "#py-testing": "content/python/basics/testing.json",
  "#py-typing": "content/python/basics/typing.json",
  "#python-history": "content/python/python-history.json",
  "#security-staff": "content/security/security-staff.json",
  "#sre-staff": "content/sre/sre-staff.json",
  "#sysdesign-fundamentals": "content/sysdesign/system-design.json",
  "#system-design-staff": "content/sysdesign/system-design-staff.json",
};

window.__SEARCH_INDEX = [
  {
    "title": "A/B Testing & Experimentation",
    "category": "AI/ML",
    "url": "docs.html#aiml-ab-testing-experimentation",
    "tags": [
      "FAANG",
      "core",
      "experimentation"
    ],
    "description": "The science of controlled experiments: sample size calculation, multiple testing, peeking, variance reduction, switchback experiments, and metrics…",
    "sections": [
      "A/B Testing Fundamentals",
      "Multiple Testing Correction",
      "Peeking Problem",
      "Variance Reduction (CUPED)",
      "Switchback Experiments"
    ]
  },
  {
    "title": "Activation Functions",
    "category": "AI/ML",
    "url": "docs.html#aiml-activation-functions",
    "tags": [
      "FAANG",
      "deep-learning",
      "activation"
    ],
    "description": "Ten activation functions with formulas, derivatives, SVGs, TF code, pros/cons, and FAANG insights — from classic sigmoid to modern GELU and SwiGLU.",
    "sections": [
      "Sigmoid / Logistic Function",
      "Tanh — Zero-Centered Saturation",
      "ReLU (Rectified Linear Unit)",
      "Leaky ReLU & Parametric ReLU (PReLU)",
      "ELU (Exponential Linear Unit)"
    ]
  },
  {
    "title": "Introduction to Neural Networks",
    "category": "AI/ML",
    "url": "docs.html#aiml-ann-history",
    "tags": [
      "FAANG",
      "deep-learning",
      "history"
    ],
    "description": "From the McCulloch-Pitts neuron to modern Transformers — a guided tour through the evolution of neural networks. Understand how each innovation built…",
    "sections": [
      "1943 — McCulloch-Pitts Neuron: The First Mathematical Neuron",
      "1958 — Rosenblatt's Perceptron: The First Learning Algorithm",
      "Activation Functions & Weight Initialization",
      "1986 — Backpropagation: Chain Rule at Scale",
      "Vanishing Gradients & Residual Connections"
    ]
  },
  {
    "title": "Computer Vision Deep Dive",
    "category": "AI/ML",
    "url": "docs.html#aiml-cv-deep-dive",
    "tags": [
      "FAANG",
      "advanced",
      "computer-vision"
    ],
    "description": "Computer Vision from image classification to self-supervised learning — with FAANG interview depth.",
    "sections": [
      "Image Classification — ResNet, EfficientNet, ViT",
      "Object Detection — YOLO, Faster R-CNN, DETR",
      "Image Segmentation — U-Net, Mask R-CNN",
      "Face Recognition — FaceNet & ArcFace",
      "Self-Supervised Learning for CV"
    ]
  },
  {
    "title": "LLM Engineering Deep Dive",
    "category": "AI/ML",
    "url": "docs.html#aiml-llm-engineering",
    "tags": [
      "FAANG",
      "staff+",
      "LLM",
      "GenAI"
    ],
    "description": "[Intuition]: LLM engineering bridges the gap between training large language models and deploying them reliably at scale. This file covers prompt…",
    "sections": [
      "Prompt Engineering Patterns",
      "RAG Architecture & Evaluation",
      "Parameter-Efficient Fine-Tuning (PEFT)",
      "RLHF & DPO for Alignment",
      "LLM Safety & Red Teaming"
    ]
  },
  {
    "title": "ML Behavioral Interview (STAR)",
    "category": "AI/ML",
    "url": "docs.html#aiml-ml-behavioral",
    "tags": [
      "FAANG",
      "interview",
      "behavioral",
      "STAR"
    ],
    "description": "[Intuition]: FAANG ML behavioral interviews require more than just the STAR format — they test your ability to make technical decisions under…",
    "sections": [
      "Tell me about a time your model failed in production",
      "How do you handle ambiguous ML requirements?",
      "Tell me about a disagreement on model approach",
      "Describe debugging a non-converging model",
      "How do you prioritize features for an ML system?"
    ]
  },
  {
    "title": "FAANG ML Chestnut Questions",
    "category": "AI/ML",
    "url": "docs.html#aiml-ml-chestnut-questions",
    "tags": [
      "FAANG",
      "interview",
      "Q&A",
      "cheat-sheet"
    ],
    "description": "30 essential Q&As asked in FAANG ML interviews — 20 core questions + 10 Staff+ questions covering distributed training, scaling laws,…",
    "sections": [
      "1. Explain the bias-variance tradeoff",
      "2. What's the difference between L1 and L2 regularization?",
      "3. How do you handle imbalanced datasets?",
      "4. Explain backpropagation in a neural network",
      "5. Why does ReLU work better than sigmoid/tanh?"
    ]
  },
  {
    "title": "ML Coding Patterns",
    "category": "AI/ML",
    "url": "docs.html#aiml-ml-coding-patterns",
    "tags": [
      "FAANG",
      "coding",
      "patterns"
    ],
    "description": "Six LeetCode-style but ML-focused coding problems: online K-Means, incremental AUC, LRU cache, O(1) moving average, rate limiter, and sliding window…",
    "sections": [
      "Online K-Means",
      "Incremental AUC Calculation",
      "LRU Cache",
      "O(1) Moving Average — SMA and EMA",
      "Rate Limiter (Token Bucket)"
    ]
  },
  {
    "title": "FAANG Company Focus",
    "category": "AI/ML",
    "url": "docs.html#aiml-ml-company-focus",
    "tags": [
      "FAANG",
      "interview",
      "company-strategy"
    ],
    "description": "**Staff+ track** Targeted interview prep for 8 top ML employers — Google, Meta, Apple, Amazon, Netflix, Microsoft, NVIDIA, OpenAI — plus Staff+ round…",
    "sections": [
      "Google",
      "Meta (Facebook)",
      "Apple",
      "Amazon",
      "Netflix"
    ]
  },
  {
    "title": "Data-Centric AI",
    "category": "AI/ML",
    "url": "docs.html#aiml-ml-data-centric",
    "tags": [
      "FAANG",
      "core",
      "data"
    ],
    "description": "Andrew Ng's data-centric approach: improving data quality, weak supervision, active learning, and data debugging often give more ROI than model…",
    "sections": [
      "Data Quality & Label Consistency",
      "Data Augmentation",
      "Weak Supervision (Snorkel)",
      "Active Learning",
      "Data Debugging"
    ]
  },
  {
    "title": "ML Fundamentals",
    "category": "AI/ML",
    "url": "docs.html#aiml-ml-fundamentals",
    "tags": [
      "FAANG",
      "core",
      "basics"
    ],
    "description": "The core concepts every ML practitioner must know: model types, evaluation, bias-variance tradeoff, cross-validation, metrics, overfitting diagnosis,…",
    "sections": [
      "What is Machine Learning?",
      "Train / Validation / Test Splits",
      "Bias-Variance Tradeoff",
      "Cross-Validation",
      "Classification Metrics"
    ]
  },
  {
    "title": "GPU Deep Dive for ML",
    "category": "AI/ML",
    "url": "docs.html#aiml-ml-gpu-deep-dive",
    "tags": [
      "FAANG",
      "infrastructure",
      "GPU",
      "performance"
    ],
    "description": "GPU architecture fundamentals — why GPUs are fast for ML, memory hierarchy, profiling model memory usage, mixed precision training, quantization,…",
    "sections": [
      "Why GPUs Are Fast",
      "GPU Memory Hierarchy",
      "Memory Profiling for ML Models",
      "Mixed Precision Training",
      "Quantization"
    ]
  },
  {
    "title": "ML Interpretability & Responsible AI",
    "category": "AI/ML",
    "url": "docs.html#aiml-ml-interpretability-fairness",
    "tags": [
      "FAANG",
      "staff+",
      "ethics"
    ],
    "description": "[Intuition]: As ML systems make higher-stakes decisions (hiring, lending, healthcare, criminal justice), interpretability and fairness transition…",
    "sections": [
      "SHAP Deep Dive with Code",
      "LIME Deep Dive with Code",
      "Integrated Gradients & Saliency Maps",
      "Counterfactual Explanations",
      "Fairness Metrics & Bias Detection"
    ]
  },
  {
    "title": "ML Leadership & Strategy for Staff+",
    "category": "AI/ML",
    "url": "docs.html#aiml-ml-leadership-strategy",
    "tags": [
      "FAANG",
      "staff+",
      "leadership"
    ],
    "description": "[Intuition]: Staff+ ML engineering at FAANG is 40% technical skill and 60% leadership. You're expected to drive technical vision across multiple…",
    "sections": [
      "Driving Technical Vision Across Orgs",
      "Influencing Without Authority",
      "Mentoring & Growing Junior ML Engineers",
      "Setting ML Roadmaps & Priorities",
      "Build vs Buy for ML Infrastructure"
    ]
  },
  {
    "title": "ML Math (Probability & Linear Algebra)",
    "category": "AI/ML",
    "url": "docs.html#aiml-ml-math",
    "tags": [
      "FAANG",
      "core",
      "mathematics"
    ],
    "description": "The mathematical foundations of ML: probability theory, linear algebra, statistics, information theory, and optimization — curated for FAANG…",
    "sections": [
      "Probability for ML",
      "Linear Algebra",
      "Statistics for ML",
      "Information Theory",
      "Optimization in ML"
    ]
  },
  {
    "title": "ML Mock Interview Walkthroughs",
    "category": "AI/ML",
    "url": "docs.html#aiml-ml-mock-interviews",
    "tags": [
      "FAANG",
      "interview",
      "mock",
      "rubric"
    ],
    "description": "[Intuition]: Interviews are a skill separate from ML knowledge. Knowing the material isn't enough — you need to structure your answers, manage time,…",
    "sections": [
      "ML System Design Mock — Design an ML Platform (Google L6)",
      "ML System Design Mock — Design a Fraud Detection System (Meta E6)",
      "ML Coding Mock — Implement Multi-Head Attention from Scratch (45 min)",
      "ML Coding Mock — Implement a Decision Tree from Scratch (30 min)",
      "Staff+ Behavioral Mock — Full Loop (Amazon L6)"
    ]
  },
  {
    "title": "ML Research Papers",
    "category": "AI/ML",
    "url": "docs.html#aiml-ml-papers",
    "tags": [
      "FAANG",
      "research",
      "papers"
    ],
    "description": "Ten canonical ML papers every FAANG candidate must know — from Attention and ResNets to GANs, VAEs, diffusion models, and scaling laws — with the key…",
    "sections": [
      "Attention Is All You Need (Vaswani et al. 2017)",
      "Deep Residual Learning (He et al. 2016)",
      "Batch Normalization (Ioffe & Szegedy 2015)",
      "Adam Optimizer (Kingma & Ba 2015)",
      "Dropout (Srivastava et al. 2014)"
    ]
  },
  {
    "title": "Production ML Operations",
    "category": "AI/ML",
    "url": "docs.html#aiml-ml-production-ops",
    "tags": [
      "FAANG",
      "staff+",
      "MLOps"
    ],
    "description": "[Intuition]: Production ML is where 90% of ML engineering happens — data pipelines, feature engineering, labeling, experiment design, deployment…",
    "sections": [
      "Online Learning & Bandits at Scale",
      "Feature Engineering Platform",
      "Data Quality Monitoring Pipelines",
      "Labeling Strategy at Scale (Active Learning, Weak Supervision, Snorkel)",
      "Experimentation with Network Effects"
    ]
  },
  {
    "title": "ML Project Structure",
    "category": "AI/ML",
    "url": "docs.html#aiml-ml-project-structure",
    "tags": [
      "FAANG",
      "system-design",
      "workflow"
    ],
    "description": "Andrew Ng-inspired ML project strategy — single-number metrics, human-level performance, error analysis, train/dev/test distributions, bias vs…",
    "sections": [
      "Setting Up ML Strategy",
      "Human-Level Performance (HLP)",
      "Error Analysis",
      "Train/Dev/Test Distributions",
      "Bias vs Variance in Deep Learning"
    ]
  },
  {
    "title": "ML Study Roadmap",
    "category": "AI/ML",
    "url": "docs.html#aiml-ml-roadmap",
    "tags": [
      "FAANG",
      "study-plan",
      "curriculum"
    ],
    "description": "Three guided study tracks from absolute beginner to Staff+ FAANG ML engineer. Choose your track based on your background and timeline: 3-Month Crash…",
    "sections": []
  },
  {
    "title": "Staff+ ML System Design",
    "category": "AI/ML",
    "url": "docs.html#aiml-ml-staff-system-design",
    "tags": [
      "FAANG",
      "staff+",
      "system-design"
    ],
    "description": "[Intuition]: Staff+ ML system design at FAANG goes beyond building a single model — you design the ML platform, infrastructure, and process that…",
    "sections": [
      "Design an ML Platform (Feature Store + Training + Serving)",
      "Design a Real-Time ML System at 10M+ QPS",
      "Design a Multi-Stage Ranking Pipeline (Retrieval → Pre-Ranking → Ranking → Re-Ranking)",
      "Design an A/B Experimentation Platform at Scale",
      "Design a Distributed Training Platform"
    ]
  },
  {
    "title": "ML System Design",
    "category": "AI/ML",
    "url": "docs.html#aiml-ml-system-design",
    "tags": [
      "FAANG",
      "system-design",
      "architecture"
    ],
    "description": "Production ML system design patterns — recommendation, fraud detection, search ranking, ad prediction, content moderation, personalized feeds,…",
    "sections": [
      "Design a Recommendation System — Two-Tower DNN Architecture",
      "Design a Fraud Detection System",
      "Design a Search Ranking System",
      "Design an Ad Prediction (CTR) System",
      "Design a Content Moderation System"
    ]
  },
  {
    "title": "Foundations from Scratch",
    "category": "AI/ML",
    "url": "docs.html#aiml-ml-zero-to-hero",
    "tags": [
      "FAANG",
      "from-scratch",
      "implementation"
    ],
    "description": "Eight from-scratch implementations inspired by Andrej Karpathy's Zero-to-Hero series — micrograd, BPE tokenizer, nanoGPT, and more — built with raw…",
    "sections": [
      "micrograd — A Tiny Autograd Engine",
      "MLP from Scratch with NumPy",
      "Manual Backpropagation — 3-Layer Network",
      "Softmax + Cross-Entropy from Scratch",
      "BPE Tokenizer from Scratch"
    ]
  },
  {
    "title": "Neural Network Training",
    "category": "AI/ML",
    "url": "docs.html#aiml-neural-network-training",
    "tags": [
      "FAANG",
      "deep-learning",
      "training"
    ],
    "description": "Weight initialization, loss functions, optimizers, normalization, regularization, LR schedules, and production-scale training — with FAANG interview…",
    "sections": [
      "Weight Initialization — Breaking Symmetry",
      "Loss Functions — Regression",
      "Loss Functions — Classification",
      "Advanced Losses — Contrastive & Triplet",
      "Optimizers — SGD to AdamW to Lion"
    ]
  },
  {
    "title": "NLP Deep Dive",
    "category": "AI/ML",
    "url": "docs.html#aiml-nlp-deep-dive",
    "tags": [
      "FAANG",
      "advanced",
      "NLP"
    ],
    "description": "Natural Language Processing from word embeddings to LLM fine-tuning — with FAANG interview depth covering Word2Vec, GloVe, FastText, CRF, BiLSTM-CRF,…",
    "sections": [
      "Word Embeddings — Distributed Representations",
      "Sequence Labeling — NER, POS, Chunking",
      "Text Classification — CNNs to Transformers",
      "Seq2Seq & Attention Mechanisms",
      "Transformer Pre-training — BERT & Its Variants"
    ]
  },
  {
    "title": "Recommendation Systems",
    "category": "AI/ML",
    "url": "docs.html#aiml-recommendation-systems",
    "tags": [
      "FAANG",
      "system-design",
      "recommender"
    ],
    "description": "Core recommendation system paradigms — collaborative filtering, matrix factorization, two-tower DNNs, multi-stage ranking, exploration strategies,…",
    "sections": [
      "Problem Setup & Data",
      "Collaborative Filtering",
      "Matrix Factorization",
      "Two-Tower DNN",
      "Multi-Stage Ranking"
    ]
  },
  {
    "title": "Reinforcement Learning & RLHF",
    "category": "AI/ML",
    "url": "docs.html#aiml-rl-rlhf",
    "tags": [
      "FAANG",
      "advanced",
      "reinforcement-learning"
    ],
    "description": "Reinforcement Learning fundamentals — MDPs, Q-learning, policy gradients, PPO, multi-armed bandits — and RLHF for LLM alignment, with FAANG interview…",
    "sections": [
      "MDP & Bellman Equations",
      "Q-Learning & Deep Q-Networks (DQN)",
      "Policy Gradients & PPO",
      "Multi-Armed Bandits & Exploration",
      "RLHF — Reinforcement Learning from Human Feedback"
    ]
  },
  {
    "title": "Supervised Learning",
    "category": "AI/ML",
    "url": "docs.html#aiml-supervised-learning",
    "tags": [
      "FAANG",
      "core",
      "supervised"
    ],
    "description": "Foundations of supervised learning: linear models, trees, ensemble methods, SVMs, and instance-based learning with FAANG-depth intuition and…",
    "sections": [
      "Linear Regression",
      "Regularized Regression (Ridge, Lasso, ElasticNet)",
      "Logistic Regression",
      "Decision Trees",
      "Random Forest"
    ]
  },
  {
    "title": "Types of Artificial Neural Networks",
    "category": "AI/ML",
    "url": "docs.html#aiml-types-of-anns",
    "tags": [
      "FAANG",
      "deep-learning",
      "architectures"
    ],
    "description": "A visual guide to the major neural network architectures — their structure, use cases, key innovations, real-world applications, and FAANG interview…",
    "sections": [
      "Multilayer Perceptron (MLP) — The Universal Approximator",
      "Convolutional Neural Network (CNN) — Spatial Feature Extractors",
      "Recurrent Neural Networks (RNN / LSTM / GRU) — Sequential Memory",
      "Generative Adversarial Network (GAN) — The Generator vs Discriminator Game",
      "Autoencoder — Compression via Bottleneck"
    ]
  },
  {
    "title": "Unsupervised Learning",
    "category": "AI/ML",
    "url": "docs.html#aiml-unsupervised-learning",
    "tags": [
      "FAANG",
      "core",
      "unsupervised"
    ],
    "description": "Clustering, dimensionality reduction, and anomaly detection: algorithms that find hidden structure in unlabeled data with FAANG-depth intuition.",
    "sections": [
      "K-Means Clustering",
      "DBSCAN",
      "Hierarchical Clustering",
      "Gaussian Mixture Models (GMM) & EM",
      "Principal Component Analysis (PCA)"
    ]
  },
  {
    "title": "Database Systems — Staff+ FAANG Interview Prep",
    "category": "Databases",
    "url": "docs.html#databases-staff",
    "tags": [
      "FAANG",
      "databases",
      "distributed-systems",
      "storage",
      "infrastructure",
      "sql",
      "nosql",
      "performance",
      "security",
      "cloud"
    ],
    "description": "Comprehensive deep-dive into database systems at Staff+ FAANG engineering level. Covers storage engine internals, ARIES crash recovery, MVCC…",
    "sections": [
      "Storage Engine Internals: B-trees, LSM-Trees & Buffer Pool",
      "ARIES Crash Recovery & Write-Ahead Logging",
      "Transaction Processing & MVCC Deep Dive",
      "Concurrency in Storage Engines: Latching & Locking",
      "Distributed SQL & NewSQL: Spanner, CockroachDB & FoundationDB"
    ]
  },
  {
    "title": "Database Fundamentals",
    "category": "Databases",
    "url": "docs.html#database-fundamentals",
    "tags": [
      "FAANG",
      "databases",
      "storage",
      "infrastructure"
    ],
    "description": "SQL indexing, transaction isolation levels, normal forms, NoSQL taxonomy, query optimization, and storage engines — everything needed for FAANG…",
    "sections": [
      "SQL Indexing",
      "ACID Transactions",
      "Isolation Levels & Anomalies",
      "Database Normalization & Denormalization",
      "NoSQL Taxonomy & Consistency Models"
    ]
  },
  {
    "title": "FAANG Engineering Facts",
    "category": "FAANG",
    "url": "docs.html#faang-facts",
    "tags": [
      "FAANG",
      "interview",
      "company-strategy",
      "reference"
    ],
    "description": "Real scale numbers, architectural decisions, and engineering culture facts from Meta, Amazon, Apple, Netflix, and Google. These are the facts that…",
    "sections": [
      "Meta (Facebook) — Social Graph at Planetary Scale",
      "Amazon — The Everything Store's Infrastructure",
      "Apple — Hardware + Software Vertical Integration",
      "Netflix — Streaming at Internet Scale",
      "Google — The Internet's Search Engine"
    ]
  },
  {
    "title": "Advanced Agent Architectures — Planning, Memory, Multi-Agent & Production",
    "category": "Gen AI",
    "url": "docs.html#genai-agent-advanced",
    "tags": [
      "FAANG",
      "staff+",
      "gen-ai",
      "agents",
      "multi-agent",
      "agent-planning",
      "agent-memory",
      "langgraph",
      "crewai",
      "autogen",
      "agent-sandbox",
      "agent-evaluation"
    ],
    "description": "Production-grade agent systems at FAANG Staff+ level require sophisticated planning, multi-agent coordination, memory architectures, sandboxed…",
    "sections": [
      "Agent Planning: Beyond ReAct — LLMCompiler, Plan-Solve, DFSDT",
      "Agent Memory Systems: Short-Term, Long-Term, Episodic & Semantic",
      "Multi-Agent Frameworks: LangGraph, CrewAI & AutoGen Patterns",
      "Agent Sandboxing & Security",
      "Production Agent Infrastructure: Queuing, Checkpointing & Observability"
    ]
  },
  {
    "title": "Alignment — RLHF, DPO, Constitutional AI & Safety Training",
    "category": "Gen AI",
    "url": "docs.html#genai-alignment",
    "tags": [
      "FAANG",
      "gen-ai",
      "llm",
      "alignment",
      "safety"
    ],
    "description": "Alignment trains LLMs to be helpful, honest, and harmless. At Staff Engineer level, you must design preference pipelines, compare RLHF vs DPO…",
    "sections": [
      "SFT: Supervised Fine-Tuning — Data Quality Over Quantity",
      "Reward Modeling: Training the Preference Predictor",
      "PPO: Proximal Policy Optimization for LLMs",
      "DPO & Variants: Simpler, Cheaper",
      "Constitutional AI: Self-Improvement"
    ]
  },
  {
    "title": "Long-Context & Prompt Caching — Window Management, Caching & Eviction",
    "category": "Gen AI",
    "url": "docs.html#genai-context-engineering",
    "tags": [
      "FAANG",
      "gen-ai",
      "long-context",
      "context-management",
      "prompt-caching",
      "kv-cache",
      "inference-optimization",
      "sliding-window",
      "staff-plus"
    ],
    "description": "At Staff level, context engineering is about systematically managing the input context budget: understanding context window mechanics,…",
    "sections": [
      "1. Context Window Mechanics &amp; Budgeting",
      "2. Lost in the Middle &amp; Positional Bias",
      "3. Prompt Caching Strategies",
      "4. Context Eviction &amp; Sliding Window",
      "5. Context-Aware Routing"
    ]
  },
  {
    "title": "Fine-Tuning & PEFT — LoRA, QLoRA, DoRA, Adapters",
    "category": "Gen AI",
    "url": "docs.html#genai-finetuning",
    "tags": [
      "FAANG",
      "gen-ai",
      "finetuning",
      "lora",
      "qlora",
      "dora",
      "peft",
      "domain-adaptation",
      "adapter-fusion"
    ],
    "description": "At Staff level, choose the right adaptation strategy: LoRA for task adaptation (~0.1% params), full FT for domain adaptation, multi-task LoRA fusion…",
    "sections": [
      "Full Fine-Tuning vs PEFT",
      "LoRA: Low-Rank Adaptation",
      "QLoRA: Quantized LoRA",
      "DoRA: Weight-Decomposed LoRA",
      "Multi-Task Fine-Tuning & Adapter Fusion"
    ]
  },
  {
    "title": "LLM Evaluation — Benchmarks, Automated Evals & Monitoring",
    "category": "Gen AI",
    "url": "docs.html#genai-harness-engineering",
    "tags": [
      "FAANG",
      "gen-ai",
      "evaluation",
      "benchmarks",
      "testing",
      "llm-evaluation",
      "monitoring"
    ],
    "description": "At Staff level, harness engineering is about building robust evaluation pipelines that measure model quality, detect regressions, and guide…",
    "sections": [
      "LLM Benchmarks Taxonomy",
      "Building an Evaluation Harness",
      "Automated Evals with LLM-as-Judge",
      "Human Evaluation at Scale",
      "Regression Testing in CI/CD"
    ]
  },
  {
    "title": "Inference Optimization — KV Cache, FlashAttention & Quantization",
    "category": "Gen AI",
    "url": "docs.html#genai-kvcache",
    "tags": [
      "FAANG",
      "gen-ai",
      "llm",
      "inference",
      "performance"
    ],
    "description": "LLM inference is the dominant cost at scale — optimizing it is a Staff Engineer's top priority. Understand KV cache memory, FlashAttention,…",
    "sections": [
      "The Inference Problem: Memory-Bound Generation",
      "KV Cache: Pre-Fill vs Decode Phase",
      "FlashAttention: Fused Attention Kernel",
      "PagedAttention & vLLM",
      "Speculative Decoding"
    ]
  },
  {
    "title": "LLM Serving — Production Inference at Scale",
    "category": "Gen AI",
    "url": "docs.html#genai-llm-serving",
    "tags": [
      "FAANG",
      "gen-ai",
      "llm-serving",
      "deployment",
      "infrastructure",
      "vllm",
      "continuous-batching",
      "autoscaling"
    ],
    "description": "LLM serving at scale requires orchestrating model deployment, continuous batching, request routing, autoscaling, and cost optimization. At Staff…",
    "sections": [
      "Serving Frameworks — vLLM, TGI, TensorRT-LLM, llama.cpp",
      "Continuous Batching — Iteration-Level Scheduling",
      "Request Routing & Autoscaling",
      "Latency Optimization — TTFT & TPOT",
      "Model Parallelism for Serving — Tensor vs Pipeline"
    ]
  },
  {
    "title": "LLM Agents — ReAct, Tool Use, Reasoning & Self-Correction",
    "category": "Gen AI",
    "url": "docs.html#genai-loop-engineering",
    "tags": [
      "FAANG",
      "gen-ai",
      "agent",
      "llm-agents",
      "reasoning",
      "tool-use",
      "react",
      "self-refine",
      "chain-of-thought",
      "tree-of-thoughts",
      "multi-agent"
    ],
    "description": "At Staff level, loop engineering is about designing reliable multi-step LLM workflows: reasoning chains, tool use, agentic loops, and…",
    "sections": [
      "Reasoning Patterns: CoT, ToT, GoT & Self-Consistency",
      "Tool Use & Function Calling",
      "Agentic Loops — ReAct Pattern",
      "Self-Correction & Reflection",
      "Multi-Agent Systems: Debate, Routing & Coordination"
    ]
  },
  {
    "title": "MCP — Model Context Protocol: Standardizing LLM-Tool Interaction",
    "category": "Gen AI",
    "url": "docs.html#genai-mcp",
    "tags": [
      "FAANG",
      "staff+",
      "gen-ai",
      "mcp",
      "model-context-protocol",
      "tools",
      "agents",
      "protocol"
    ],
    "description": "MCP (Model Context Protocol) is an open standard by Anthropic for connecting LLMs to external tools, data sources, and services. At Staff+ level, you…",
    "sections": [
      "What is MCP? — The Problem It Solves",
      "MCP Architecture: Host, Client & Server",
      "MCP Primitives: Resources, Tools & Prompts",
      "Building Production MCP Servers",
      "MCP vs A2A vs Function Calling: A Staff+ Comparison"
    ]
  },
  {
    "title": "Mixture of Experts — MoE Architecture, Routing & Scaling",
    "category": "Gen AI",
    "url": "docs.html#genai-moe",
    "tags": [
      "FAANG",
      "gen-ai",
      "moe",
      "architecture",
      "routing",
      "scaling",
      "mixture-of-experts"
    ],
    "description": "Mixture of Experts (MoE) scales model capacity without proportional compute cost by activating only a subset of parameters per token. At Staff level,…",
    "sections": [
      "What is MoE? — Sparse Activation at Scale",
      "Routing & Top-K Gating — The Sparse Gate",
      "Load Balancing & Auxiliary Loss — Preventing Expert Collapse",
      "All-to-All Communication — The MoE Bottleneck",
      "Expert Capacity & Token Dropping — Graceful Degradation"
    ]
  },
  {
    "title": "Multimodal LLMs — Vision, Audio & Video at Scale",
    "category": "Gen AI",
    "url": "docs.html#genai-multimodal",
    "tags": [
      "FAANG",
      "staff+",
      "gen-ai",
      "multimodal",
      "vision",
      "audio",
      "video",
      "gpt-4v",
      "gemini",
      "claude-vision"
    ],
    "description": "Multimodal LLMs process text, images, audio, and video in a single model. At FAANG Staff+ level, you must design systems that handle high-throughput…",
    "sections": [
      "Multimodal Architecture: How LLMs See and Hear",
      "Vision at Scale: Image Processing Pipelines",
      "Audio & Video: Speech, Transcription & Temporal Reasoning",
      "Multimodal Caching, Batching & Cost Optimization",
      "Cross-Provider Multimodal Abstraction"
    ]
  },
  {
    "title": "LLM Observability — Monitoring, Tracing & Evaluation at Scale",
    "category": "Gen AI",
    "url": "docs.html#genai-observability",
    "tags": [
      "FAANG",
      "staff+",
      "gen-ai",
      "observability",
      "monitoring",
      "tracing",
      "evaluation",
      "drift-detection",
      "cost-tracking"
    ],
    "description": "LLM observability is more complex than traditional application observability because LLMs are non-deterministic, their outputs are unstructured, and…",
    "sections": [
      "The Three Pillars of LLM Observability",
      "Automated Quality Evaluation: LLM-as-Judge & Classifiers",
      "Tracing: End-to-End Visibility Across the LLM Stack",
      "Drift Detection: Model, Data & Behaviour Monitoring",
      "Cost Observability: Attribution, Budgeting & Optimisation"
    ]
  },
  {
    "title": "Pre-Training LLMs at Scale — Data, Recipes & Distributed Training",
    "category": "Gen AI",
    "url": "docs.html#genai-pretraining",
    "tags": [
      "FAANG",
      "gen-ai",
      "llm",
      "training",
      "distributed"
    ],
    "description": "Pre-training is the most compute-intensive phase — costing $10M-100M for frontier models. At Staff Engineer level, you must design data pipelines,…",
    "sections": [
      "The Data Pipeline: From Raw Web to Training Examples",
      "Data Mixing: The Secret Sauce",
      "The Scaling Law: Predict Optimal Model Size for Budget",
      "Distributed Training: 3D Parallelism & the Communication Wall",
      "FSDP: Fully Sharded Data Parallelism — ZeRO Stages"
    ]
  },
  {
    "title": "Prompt Engineering — Techniques, Strategies & Production Pipelines",
    "category": "Gen AI",
    "url": "docs.html#genai-prompt-engineering",
    "tags": [
      "FAANG",
      "gen-ai",
      "prompt-engineering",
      "context-management",
      "dspy",
      "rag",
      "prompt-caching"
    ],
    "description": "At Staff level, prompt engineering is not about clever templates — it's about systematically managing the input context: choosing the right prompting…",
    "sections": [
      "Prompt Engineering: Zero-Shot, Few-Shot, Chain-of-Thought",
      "Structured Output: JSON Mode & Constrained Decoding",
      "DSPy: Compiling Prompt Pipelines",
      "The Context Window: Mechanics & Limits",
      "Lost in the Middle: Positional Bias"
    ]
  },
  {
    "title": "RAG — Retrieval-Augmented Generation at Scale",
    "category": "Gen AI",
    "url": "docs.html#genai-rag",
    "tags": [
      "FAANG",
      "gen-ai",
      "rag",
      "retrieval",
      "embedding",
      "vector-db",
      "reranking",
      "hybrid-search",
      "production-rag"
    ],
    "description": "RAG (Retrieval-Augmented Generation) is the dominant architecture for grounding LLMs in external knowledge. At Staff level, you must design RAG…",
    "sections": [
      "RAG Architecture Overview",
      "Chunking Strategies",
      "Embedding Models & Vector Databases",
      "Hybrid Search & Reranking",
      "RAG Evaluation"
    ]
  },
  {
    "title": "LLM Security & Guardrails — Defending Production AI Systems",
    "category": "Gen AI",
    "url": "docs.html#genai-security",
    "tags": [
      "FAANG",
      "staff+",
      "gen-ai",
      "security",
      "guardrails",
      "prompt-injection",
      "red-teaming",
      "pii",
      "privacy"
    ],
    "description": "LLM security is fundamentally different from traditional application security. The attack surface includes prompt injection, data poisoning, model…",
    "sections": [
      "The LLM Attack Surface: Classes of Threats",
      "Prompt Injection: Detection, Prevention & Mitigation",
      "Guardrails: Input Validation, Output Verification & Content Safety",
      "Red-Teaming, Adversarial Testing & Continuous Evaluation",
      "Data Privacy: PII Redaction, Confidentiality & Compliance"
    ]
  },
  {
    "title": "AI Skills Architecture — Composable Capabilities at Scale",
    "category": "Gen AI",
    "url": "docs.html#genai-skills",
    "tags": [
      "FAANG",
      "staff+",
      "gen-ai",
      "skills",
      "semantic-kernel",
      "composable-ai",
      "skill-registry",
      "ai-governance"
    ],
    "description": "AI Skills are composable, reusable capability modules that bridge the gap between stateless tools and autonomous agents. At FAANG Staff+ level, you…",
    "sections": [
      "What Are AI Skills? — Skills vs Tools vs Agents",
      "Skill Definition & Composition Patterns",
      "Skill Registries, Discovery & Cross-Team Sharing",
      "Semantic Kernel Skills Pattern",
      "Skill Security & Governance"
    ]
  },
  {
    "title": "Synthetic Data Generation — Training, Evaluation & Alignment at Scale",
    "category": "Gen AI",
    "url": "docs.html#genai-synthetic-data",
    "tags": [
      "FAANG",
      "staff+",
      "gen-ai",
      "synthetic-data",
      "rlhf",
      "dpo",
      "model-collapse",
      "data-augmentation",
      "evaluation"
    ],
    "description": "Synthetic data is AI-generated training data used to augment, replace, or bootstrap real datasets. At FAANG Staff+ level, synthetic data is the…",
    "sections": [
      "The Role of Synthetic Data in LLM Development",
      "Preference Data: RLHF & DPO at Scale",
      "Synthetic Evaluation Benchmarks: Calibrated Testing at Scale",
      "Avoiding Model Collapse & Distribution Shift",
      "FAANG Q&A — Synthetic Data Generation"
    ]
  },
  {
    "title": "Tool Use & Function Calling — Architectures at Scale",
    "category": "Gen AI",
    "url": "docs.html#genai-tools",
    "tags": [
      "FAANG",
      "staff+",
      "gen-ai",
      "tools",
      "function-calling",
      "structured-output",
      "tool-safety",
      "tool-caching"
    ],
    "description": "Tool use is the foundation of LLM agency. At FAANG Staff+ level, you must design tool systems that handle 1000+ tool definitions, streaming parallel…",
    "sections": [
      "Tool Use Fundamentals: How LLMs Learn to Call Tools",
      "Tool Schema Design: JSON Schema for LLMs",
      "Structured Output: JSON Mode, Constrained Decoding & Grammar",
      "Parallel & Sequential Tool Calling",
      "Tool Security: Injection, Sandboxing & Governance"
    ]
  },
  {
    "title": "Transformer Architecture — Attention Is All You Need Deep Dive",
    "category": "Gen AI",
    "url": "docs.html#genai-transformer-architecture",
    "tags": [
      "FAANG",
      "gen-ai",
      "transformer",
      "attention",
      "foundations"
    ],
    "description": "The original Transformer (Vaswani et al., 2017) is the foundation of every modern LLM. At Staff level, you must understand the encoder-decoder…",
    "sections": [
      "The Original Transformer: Encoder-Decoder at a Glance",
      "Scaled Dot-Product Attention — The Core Equation",
      "Multi-Head Attention — Ensemble of Subspaces",
      "Positional Encoding — Sinusoidal vs Learned",
      "Cross-Attention — How the Decoder Reads the Encoder"
    ]
  },
  {
    "title": "LLM Architecture — Transformers, Scaling Laws & Training",
    "category": "Gen AI",
    "url": "docs.html#genai-what-is-llm",
    "tags": [
      "FAANG",
      "gen-ai",
      "llm",
      "architecture"
    ],
    "description": "A decoder-only Transformer (GPT-style) is the dominant LLM architecture. At FAANG Staff level, you must understand every design knob: attention…",
    "sections": [
      "The Transformer Decoder: Anatomy of a Block",
      "Attention Mechanisms: MHA → MQA → GQA → MLA",
      "Positional Encoding: RoPE, ALiBi, YaRN, NTK",
      "FFN Variants: ReLU, GELU, SiLU, SwiGLU",
      "Scaling Laws Deep Dive — Beyond Chinchilla"
    ]
  },
  {
    "title": "Computer Networks — Staff+ FAANG Interview Prep",
    "category": "Computer Networks",
    "url": "docs.html#computer-networks",
    "tags": [
      "FAANG",
      "networking",
      "protocols",
      "infrastructure",
      "distributed-systems",
      "security",
      "datacenter",
      "observability"
    ],
    "description": "Comprehensive deep-dive into computer networking at Staff+ FAANG engineering level. Covers protocol mechanics, data center topologies, eBPF/XDP,…",
    "sections": [
      "OSI Model & TCP/IP Protocol Mechanics",
      "HTTP Evolution, gRPC & Protocol Design",
      "DNS Architecture & Anycast Routing",
      "Load Balancing, Proxy Patterns & Global Traffic",
      "CDN Architecture & Caching Strategies"
    ]
  },
  {
    "title": "Object-Oriented Programming — Staff+ FAANG Interview Prep",
    "category": "Object-Oriented Programming",
    "url": "docs.html#oop-staff",
    "tags": [
      "FAANG",
      "OOP",
      "design-patterns",
      "SOLID",
      "DDD",
      "GRASP",
      "abstraction",
      "polymorphism",
      "inheritance",
      "Staff+"
    ],
    "description": "Comprehensive deep-dive into Object-Oriented Programming at Staff+ FAANG engineering level. Covers OOP fundamentals, SOLID principles, encapsulation…",
    "sections": [
      "OOP Fundamentals & The Paradigm Shift",
      "SOLID Principles in Real-World Codebases",
      "Encapsulation, Abstraction & Information Hiding",
      "Inheritance, Composition & Delegation",
      "Polymorphism: Static, Dynamic & Ad-Hoc"
    ]
  },
  {
    "title": "Operating Systems — Staff+ FAANG Interview Prep",
    "category": "Operating Systems",
    "url": "docs.html#operating-systems",
    "tags": [
      "FAANG",
      "operating-systems",
      "linux",
      "kernel",
      "infrastructure",
      "virtualization",
      "containers",
      "performance",
      "security",
      "ebpf",
      "storage"
    ],
    "description": "Comprehensive deep-dive into operating systems at Staff+ FAANG engineering level. Covers process/scheduler evolution, memory management, file…",
    "sections": [
      "Process, Thread & Scheduler Evolution",
      "Memory Management: Virtual Memory, Paging & NUMA",
      "File Systems & Storage Stack",
      "Scheduling: CFS → EEVDF & Real-Time Considerations",
      "I/O Architecture: Interrupts → io_uring → DPDK → XDP"
    ]
  },
  {
    "title": "Staff+ Behavioral & Leadership Interview Preparation",
    "category": "behavioral",
    "url": "docs.html#behavioral-staff",
    "tags": [
      "behavioral",
      "leadership",
      "staff-plus",
      "interview-prep",
      "faang",
      "career"
    ],
    "description": "Comprehensive Staff+ guide covering behavioral interviews, leadership without authority, technical vision, conflict resolution, mentorship, executive…",
    "sections": [
      "Leadership & Influence Without Authority",
      "Technical Vision & Strategy Articulation",
      "Conflict Resolution & Stakeholder Navigation",
      "Mentorship, Sponsorship & Amplifying Impact",
      "Communication & Executive Presence"
    ]
  },
  {
    "title": "Staff+ Career Navigation",
    "category": "Career",
    "url": "docs.html#career-staff",
    "tags": [],
    "description": "",
    "sections": [
      "The Staff+ Career Landscape: Levels, Tracks & Expectations",
      "Preparing Your Staff+ Promotion Packet",
      "Staff+ Resume & LinkedIn Optimization",
      "Navigating the Staff+ Interview Process",
      "Negotiating Staff+ Offers: TC, Equity & Sign-on"
    ]
  },
  {
    "title": "Staff+ Engineering Patterns — FAANG Interview Prep",
    "category": "Engineering Patterns",
    "url": "docs.html#engineering-patterns-staff",
    "tags": [
      "FAANG",
      "staff-plus",
      "engineering-patterns",
      "leadership",
      "strategy",
      "mentorship",
      "career",
      "Staff+"
    ],
    "description": "Comprehensive guide to the Staff+ engineer role at FAANG — the patterns, strategies, and mindsets that separate Staff+ engineers from Senior. Covers…",
    "sections": [
      "1. The Staff+ Engineer Role: Scope, Impact & Expectations",
      "2. Technical Strategy: Writing, Communicating & Executing",
      "3. Architecture Decision Records (ADRs)",
      "4. Design Doc Reviews: Running Effective Reviews at Scale",
      "5. Decision-Making Frameworks: CIRCLES, RICE, DACI & More"
    ]
  },
  {
    "title": "Product Sense for Staff+ Engineers",
    "category": "Product Sense",
    "url": "docs.html#product-sense-staff",
    "tags": [],
    "description": "",
    "sections": [
      "Product Sense for Staff+: Why It Matters",
      "User-Centric Thinking: Personas, Needs & Jobs to Be Done",
      "Problem Definition: The Most Underrated Skill",
      "Metrics-Driven Product Thinking",
      "Prioritization Frameworks: RICE, ICE & Opportunity Scoring"
    ]
  },
  {
    "title": "Data Structures & Algorithms — Staff+ FAANG Interview Prep",
    "category": "Programming",
    "url": "docs.html#dsa-staff",
    "tags": [
      "dsa",
      "algorithms",
      "data-structures",
      "staff-plus",
      "interview-prep",
      "advanced"
    ],
    "description": "Data Structures & Algorithms at Staff+ FAANG depth. Covers complexity analysis, advanced graph algorithms, dynamic programming optimization, segment…",
    "sections": [
      "1. Foundations: Time & Space Complexity Mastery",
      "2. Arrays & Strings at Scale",
      "3. Linked Lists & Trees in Production Systems",
      "4. Advanced Graph Algorithms",
      "5. Advanced Dynamic Programming"
    ]
  },
  {
    "title": "Algorithms & Patterns",
    "category": "Python",
    "url": "docs.html#py-algorithms",
    "tags": [
      "FAANG",
      "Python",
      "algorithms",
      "coding"
    ],
    "description": "The core algorithmic patterns that appear in ~80% of FAANG coding interviews. Master these skeletons and you can adapt them to novel problems on the…",
    "sections": [
      "Binary Search — Left & Right Bound Variants",
      "Two-Pointer & Sliding Window",
      "Dynamic Programming — Memoization vs Tabulation",
      "Backtracking — Permutations, Subsets, N-Queens",
      "BFS & DFS — Graph/Tree Traversal Templates"
    ]
  },
  {
    "title": "API Handling",
    "category": "Python",
    "url": "docs.html#py-basics-api",
    "tags": [
      "FAANG",
      "Python",
      "API"
    ],
    "description": "Backend and ML engineering roles at FAANG require designing resilient API clients. This covers session pooling, retry logic, async HTTP, rate…",
    "sections": [
      "Resilient HTTP with requests",
      "Async HTTP — aiohttp",
      "Rate Limiting",
      "Authentication — JWT & OAuth2",
      "Circuit Breaker Pattern"
    ]
  },
  {
    "title": "Time & Space Complexity",
    "category": "Python",
    "url": "docs.html#py-complexity",
    "tags": [
      "FAANG",
      "Python",
      "complexity"
    ],
    "description": "Mastering Big-O analysis is table stakes at FAANG. This covers complexity of all built-in Python operations, amortized analysis, space complexity,…",
    "sections": [
      "Big-O Complexity of Python Built-ins",
      "Amortized Analysis: Dynamic Arrays",
      "Recursion & Stack Space Complexity",
      "Space Complexity Patterns",
      "Complexity of Sorting Algorithms"
    ]
  },
  {
    "title": "Multithreading & Concurrency",
    "category": "Python",
    "url": "docs.html#py-basics-concurrency",
    "tags": [
      "FAANG",
      "Python",
      "concurrency",
      "advanced"
    ],
    "description": "Python concurrency is the single most common topic in FAANG mid-to-senior Python interviews. You must understand the GIL, when threading helps…",
    "sections": [
      "1. Multithreading — The GIL Tax (I/O Wins, CPU Loses)",
      "2. Multiprocessing — True Parallelism for CPU-Bound Work",
      "3. Asyncio — 10K Connections on One Thread",
      "4. GIL Deep Dive — What, Why, and Python 3.13+ No-GIL",
      "5. Thread Safety — Locks, Deadlocks, and Correctness"
    ]
  },
  {
    "title": "Data Types & Operations",
    "category": "Python",
    "url": "docs.html#py-basics-datatypes",
    "tags": [
      "FAANG",
      "Python",
      "data-types"
    ],
    "description": "Python's type system has subtleties that trip up even experienced engineers in FAANG interviews. Mutability, identity vs equality, interning, and the…",
    "sections": [
      "Mutability — The Foundation",
      "Identity vs Equality: is vs ==",
      "The Hash Contract",
      "Type Conversion & Numeric Types",
      "String Internals & Operations"
    ]
  },
  {
    "title": "Design Docs & Technical Planning",
    "category": "Python",
    "url": "docs.html#py-design-docs",
    "tags": [
      "FAANG",
      "Python",
      "design-docs",
      "Staff+",
      "advanced"
    ],
    "description": "Writing effective design docs for Python projects at FAANG: templates, review process, tradeoff analysis, migration planning, and rollout strategies.",
    "sections": [
      "1. Why Write a Design Doc?",
      "2. Design Doc Template — the Google Standard",
      "3. Tradeoff Analysis — Structured Decision Making",
      "4. Migration Planning — Phased Rollouts and Rollbacks",
      "5. Staff+ Patterns — Technical Vision and Org-Level Planning"
    ]
  },
  {
    "title": "Built-in Collections",
    "category": "Python",
    "url": "docs.html#py-ds-builtins",
    "tags": [
      "FAANG",
      "Python",
      "data-structures"
    ],
    "description": "Python's standard library collections are your first-choice tools in any FAANG interview. Knowing their internals, exact complexities, and…",
    "sections": [
      "list — Dynamic Array",
      "dict — Hash Map",
      "set & frozenset — Hash Set",
      "deque — O(1) Both Ends",
      "FAANG Patterns — Frequency Map & Sliding Window"
    ]
  },
  {
    "title": "Graphs & Networks",
    "category": "Python",
    "url": "docs.html#py-ds-graph",
    "tags": [
      "FAANG",
      "Python",
      "data-structures",
      "graph",
      "Staff+",
      "distributed-graph",
      "pregel"
    ],
    "description": "Graphs are the most tested data structure at FAANG. Mastering BFS, DFS, topological sort, Union-Find, and shortest path algorithms is non-negotiable…",
    "sections": [
      "Graph Representation",
      "BFS & DFS — Traversal Templates",
      "Topological Sort — Kahn's Algorithm & DFS",
      "Union-Find (Disjoint Set Union)",
      "Shortest Paths — Dijkstra & Bellman-Ford"
    ]
  },
  {
    "title": "Priority Queues & Heaps",
    "category": "Python",
    "url": "docs.html#py-ds-heap",
    "tags": [
      "FAANG",
      "Python",
      "data-structures",
      "heap",
      "Staff+",
      "fibonacci-heap",
      "priority-queue"
    ],
    "description": "Heaps are the backbone of scheduling, Dijkstra's algorithm, and stream processing. Python's heapq is always a min-heap — knowing how to adapt it is a…",
    "sections": [
      "Heap Fundamentals & Complexity",
      "Max-Heap & Custom Priority",
      "Top-K Elements & K-Way Merge",
      "Median of a Data Stream — Two Heaps",
      "Dijkstra's Algorithm — Heap-Based"
    ]
  },
  {
    "title": "Linked Lists",
    "category": "Python",
    "url": "docs.html#py-ds-linkedlist",
    "tags": [
      "FAANG",
      "Python",
      "data-structures",
      "linked-list"
    ],
    "description": "Linked lists test pointer manipulation and in-place algorithms. FAANG interviewers love them because bugs are subtle. Master Floyd's cycle detection,…",
    "sections": [
      "Implementation & Basic Operations",
      "Reversal — In-Place & Recursive",
      "Floyd's Cycle Detection",
      "Slow/Fast Pointer Patterns",
      "Merge Two Sorted Lists & Merge K Lists"
    ]
  },
  {
    "title": "Stacks & Queues",
    "category": "Python",
    "url": "docs.html#py-ds-stackqueue",
    "tags": [
      "FAANG",
      "Python",
      "data-structures",
      "stack-queue",
      "Staff+",
      "concurrent-queues",
      "ring-buffer"
    ],
    "description": "Stacks and queues appear in nearly every FAANG interview — often as the hidden backbone of a 'hard' problem. The monotonic stack and queue-based BFS…",
    "sections": [
      "Stack & Queue Implementations",
      "Min Stack — O(1) getMin",
      "Monotonic Stack — Next Greater / Smaller Element",
      "Queue Using Two Stacks",
      "Sliding Window Maximum — Monotonic Deque"
    ]
  },
  {
    "title": "Trees & BSTs",
    "category": "Python",
    "url": "docs.html#py-ds-tree",
    "tags": [
      "FAANG",
      "Python",
      "data-structures",
      "tree",
      "Staff+",
      "b-tree",
      "lsm-tree"
    ],
    "description": "Trees are in every FAANG interview. Beyond basic traversals, you must know LCA, serialize/deserialize, diameter, BST operations, and when to go…",
    "sections": [
      "Tree Node & Traversal Templates",
      "Height, Diameter & Balance",
      "Lowest Common Ancestor (LCA)",
      "Serialize & Deserialize Binary Tree",
      "BST Operations & Validation"
    ]
  },
  {
    "title": "Exception Handling",
    "category": "Python",
    "url": "docs.html#py-exceptions",
    "tags": [
      "FAANG",
      "Python",
      "exceptions",
      "core-patterns"
    ],
    "description": "Python exception handling from basics to Staff+ patterns: try/except/else/finally, exception chaining, context suppression, custom exceptions, and…",
    "sections": [
      "1. The Full try Block — else and finally",
      "2. Custom Exceptions — When and How",
      "3. Exception Chaining and Suppression",
      "4. Exception Suppression in the Standard Library",
      "5. Exception Safety — Resource Cleanup Guarantees"
    ]
  },
  {
    "title": "File Handling",
    "category": "Python",
    "url": "docs.html#py-basics-files",
    "tags": [
      "FAANG",
      "Python",
      "file-handling"
    ],
    "description": "File handling at FAANG goes beyond basic read/write. Context managers, large file processing, serialization formats, and memory-mapped files are all…",
    "sections": [
      "Context Managers — The Right Way",
      "Custom Context Managers",
      "Serialization — JSON, CSV, Pickle",
      "Large File Processing",
      "pathlib & os.path Patterns"
    ]
  },
  {
    "title": "Functional Programming Patterns",
    "category": "Python",
    "url": "docs.html#py-functional",
    "tags": [
      "FAANG",
      "Python",
      "functional programming",
      "core-patterns"
    ],
    "description": "Python functional programming from comprehensions to Staff+ patterns: itertools, functools, lazy evaluation, purity, and composition.",
    "sections": [
      "1. Comprehensions and Generator Expressions",
      "2. map, filter, reduce — And Why You Usually Don't Need Them",
      "3. itertools — The Power Tool",
      "4. functools — Partial, lru_cache, and compose",
      "5. Lazy Evaluation — Generators and Memory Efficiency"
    ]
  },
  {
    "title": "Google Staff Culture — Python Edition",
    "category": "Python",
    "url": "docs.html#py-google-culture",
    "tags": [
      "FAANG",
      "Python",
      "Google",
      "Staff+",
      "advanced"
    ],
    "description": "Google's engineering culture as it applies to Python engineers: readability process, code review standards, SRE, OKRs, promotion, and writing code at…",
    "sections": [
      "1. Readability — Google's Code Review Standard",
      "2. SRE Principles — Writing Production-Ready Python",
      "3. OKRs and Impact — Framing Python Work",
      "4. Promotion — From L5 to L6+ at FAANG",
      "5. Staff+ Patterns — Design Docs, Technical Vision, and Mentorship"
    ]
  },
  {
    "title": "Input &amp; Output",
    "category": "Python",
    "url": "docs.html#py-basics-io",
    "tags": [
      "FAANG",
      "Python",
      "I/O"
    ],
    "description": "Reading user input, printing output, string formatting, and I/O internals — buffering, file descriptors, encoding pitfalls, and memory-mapped I/O.…",
    "sections": [
      "Basic Output (print) — Buffers & Streams",
      "User Input, Encoding & Edge Cases",
      "F-strings — Performance & Pitfalls",
      "File I/O — Open Modes & Binary Safety",
      "Memory-Mapped I/O (mmap) — Zero-Copy Reads"
    ]
  },
  {
    "title": "Logging & Observability",
    "category": "Python",
    "url": "docs.html#py-logging",
    "tags": [
      "FAANG",
      "Python",
      "logging",
      "observability",
      "Staff+",
      "advanced"
    ],
    "description": "Python logging from basics to Staff+ FAANG depth: structured logging, OpenTelemetry, correlation IDs, PII redaction, sampling, log aggregation, and…",
    "sections": [
      "1. Logging Fundamentals — The logging Module",
      "2. Structured Logging with JSON",
      "3. OpenTelemetry — Traces, Metrics, Logs",
      "4. Correlation IDs and Context Propagation",
      "5. PII Redaction and Log Safety"
    ]
  },
  {
    "title": "Loops & Control Flow",
    "category": "Python",
    "url": "docs.html#py-basics-loops",
    "tags": [
      "FAANG",
      "Python",
      "control-flow"
    ],
    "description": "Python's iteration model goes far deeper than for/while. Generators, the iterator protocol, and itertools are key tools for memory-efficient and…",
    "sections": [
      "Iterator Protocol",
      "Generators — Lazy Evaluation",
      "itertools — The FAANG Toolkit",
      "Comprehensions & Functional Tools",
      "Loop Control & Pattern Skeletons"
    ]
  },
  {
    "title": "Memory Management & GC",
    "category": "Python",
    "url": "docs.html#py-memory",
    "tags": [
      "FAANG",
      "Python",
      "memory",
      "core-patterns"
    ],
    "description": "Python memory management from reference counting to Staff+ GC tuning: refcounts, cyclic GC, weakrefs, memory profiling, and leak detection.",
    "sections": [
      "1. Reference Counting — The Primary GC",
      "2. Cyclic Garbage Collector — Generational GC",
      "3. Weak References — Break Cycles, Cache Smarter",
      "4. Memory Profiling — Finding Leaks and Waste",
      "5. Staff+ Patterns — Container Optimization and GC Tuning"
    ]
  },
  {
    "title": "Modules, Packages & Import System",
    "category": "Python",
    "url": "docs.html#py-modules",
    "tags": [
      "FAANG",
      "Python",
      "modules",
      "core-patterns"
    ],
    "description": "Python's import system from basics to Staff+ depth: module caching, relative vs absolute imports, namespace packages, lazy loading, and large-scale…",
    "sections": [
      "1. How Python Finds and Loads Modules",
      "2. Absolute vs Relative Imports — The Right Choice",
      "3. __pycache__ and Bytecode Caching",
      "4. Namespace Packages",
      "5. Lazy Loading and Large Package Architecture"
    ]
  },
  {
    "title": "OOP & Design Patterns",
    "category": "Python",
    "url": "docs.html#py-oop",
    "tags": [
      "FAANG",
      "Python",
      "OOP",
      "advanced",
      "design-patterns",
      "metaclasses",
      "Staff+"
    ],
    "description": "Python OOP from beginner to Staff+ FAANG depth: class mechanics, inheritance, dunder contracts, dataclasses, decorators, design patterns,…",
    "sections": [
      "1. Object Fundamentals — __init__, __new__, and Methods",
      "2. Inheritance, MRO, and Encapsulation",
      "3. Dunder Method Contract — The Full Protocol",
      "4. Dataclasses, __slots__, ABCs, and Protocols",
      "5. Decorators and Context Managers"
    ]
  },
  {
    "title": "Performance Optimization",
    "category": "Python",
    "url": "docs.html#py-performance",
    "tags": [
      "FAANG",
      "Python",
      "performance",
      "advanced"
    ],
    "description": "Python performance from profiling to Staff+ optimization: cProfile, __slots__, array, multiprocessing, asyncio, C extensions, and JIT compilation.",
    "sections": [
      "1. Profiling — Measure Before You Optimize",
      "2. Data Structure Choices — Memory and Speed",
      "3. Concurrency — Threading, Multiprocessing, Async",
      "4. C Extensions, Cython, and JIT",
      "5. Staff+ Patterns — System-Wide Optimization Strategy"
    ]
  },
  {
    "title": "Python Security Patterns",
    "category": "Python",
    "url": "docs.html#py-security",
    "tags": [
      "FAANG",
      "Python",
      "security",
      "Staff+",
      "advanced"
    ],
    "description": "Python security from basics to Staff+ FAANG depth: injection prevention, SAST, dependency scanning, secrets management, pickle risks, sandboxing, and…",
    "sections": [
      "1. Injection Prevention — SQL, Command, and Template Injection",
      "2. SAST and Dependency Scanning",
      "3. Secrets Management",
      "4. Pickle Risks and Safely Deserializing Data",
      "5. Sandboxing and Process Isolation"
    ]
  },
  {
    "title": "Testing & Mocking",
    "category": "Python",
    "url": "docs.html#py-testing",
    "tags": [
      "FAANG",
      "Python",
      "testing",
      "core-patterns"
    ],
    "description": "Python testing from pytest basics to Staff+ FAANG patterns: parametrize, fixtures, mocking, property-based testing, test doubles, coverage…",
    "sections": [
      "1. pytest Fundamentals — Structure and Idioms",
      "2. Fixtures — Scoped Setup and Teardown",
      "3. Mocking — unittest.mock Patterns",
      "4. Property-Based Testing",
      "5. Staff+ Patterns — Integration, Flaky Tests, and CI Strategy"
    ]
  },
  {
    "title": "Type Hints & Mypy",
    "category": "Python",
    "url": "docs.html#py-typing",
    "tags": [
      "FAANG",
      "Python",
      "typing",
      "core-patterns"
    ],
    "description": "Python type hints from basics to Staff+ patterns: generics, Protocols, overload, TypedDict, type narrowing, variance, and mypy strict mode.",
    "sections": [
      "1. Basic Type Hints — Syntax",
      "2. Type Aliases, NewType, and Callable",
      "3. Generics — TypeVar and Constraints",
      "4. Structural Subtyping — Protocols",
      "5. Overload, TypedDict, and Literal"
    ]
  },
  {
    "title": "History of Python",
    "category": "Python",
    "url": "docs.html#python-history",
    "tags": [],
    "description": "Python was created by Guido van Rossum and first released in 1991. The language emphasizes readability, simplicity, and explicitness — famously…",
    "sections": []
  },
  {
    "title": "Security Engineering — Staff+ FAANG Interview Prep",
    "category": "Security",
    "url": "docs.html#security-staff",
    "tags": [
      "FAANG",
      "security",
      "cryptography",
      "IAM",
      "zero-trust",
      "supply-chain",
      "compliance",
      "appsec",
      "Staff+"
    ],
    "description": "Comprehensive deep-dive into Security Engineering at Staff+ FAANG engineering level. Covers security foundations (CIA, STRIDE, zero trust), IAM…",
    "sections": [
      "1. Security Foundations: Threat Modeling, CIA & Zero Trust",
      "2. Identity & Access Management: AuthN, AuthZ, RBAC & ABAC",
      "3. Authentication: OAuth 2.0, OIDC, SAML & Passwordless",
      "4. Secrets Management: Encryption, Rotation & Vault",
      "5. Network Security: mTLS, Zero Trust Networks & Firewalls"
    ]
  },
  {
    "title": "Site Reliability Engineering — Staff+ FAANG Interview Prep",
    "category": "Site Reliability Engineering",
    "url": "docs.html#sre-staff",
    "tags": [
      "FAANG",
      "SRE",
      "reliability",
      "SLO",
      "error-budget",
      "incident-management",
      "capacity-planning",
      "observability",
      "chaos-engineering",
      "Staff+"
    ],
    "description": "Comprehensive deep-dive into Site Reliability Engineering at Staff+ FAANG engineering level. Covers SRE foundations (SLIs, SLOs, error budgets),…",
    "sections": [
      "1. SRE Foundations: SLIs, SLOs & Error Budgets",
      "2. Monitoring & Observability: Metrics, Traces, Logs",
      "3. Alerting & On-Call: Reduce Fatigue, Improve Signal",
      "4. Incident Management: Command, Control & Communication",
      "5. Capacity Planning: Forecasting, Modeling & Right-Sizing"
    ]
  },
  {
    "title": "API Design for Staff+ Engineers",
    "category": "API Design",
    "url": "docs.html#api-design-staff",
    "tags": [],
    "description": "",
    "sections": [
      "API Design Foundations: REST, GraphQL, gRPC & When to Use Each",
      "API-First Design: Contracts, Specs & Code Generation",
      "Versioning Strategies: Breaking vs Non-Breaking Changes",
      "Pagination, Filtering & Sorting at Scale",
      "Rate Limiting, Throttling & Quota Management"
    ]
  },
  {
    "title": "Distributed Systems — Staff+ FAANG Interview Prep",
    "category": "Distributed Systems",
    "url": "docs.html#distributed-systems-staff",
    "tags": [
      "FAANG",
      "distributed-systems",
      "consensus",
      "replication",
      "stream-processing",
      "scheduling",
      "microservices",
      "chaos-engineering",
      "global-scale",
      "Staff+"
    ],
    "description": "Comprehensive deep-dive into Distributed Systems at Staff+ FAANG engineering level. Covers foundations (CAP, FLP, fallacies), consensus (Paxos, Raft,…",
    "sections": [
      "1. Distributed Systems Foundations: Fallacies, CAP, FLP & Beyond",
      "2. Consensus: Paxos, Raft, Zab & Implementations",
      "3. Time, Order & Coordination: Clocks, Leases & Barriers",
      "4. Distributed Storage: GFS, Colossus, HDFS, Ceph & Object Stores",
      "5. Distributed Transactions: 2PC, Percolator, Calvin & Saga"
    ]
  },
  {
    "title": "System Design — Staff+ FAANG Interview Prep",
    "category": "System Design",
    "url": "docs.html#system-design-staff",
    "tags": [
      "FAANG",
      "system-design",
      "distributed-systems",
      "scalability",
      "interview-prep",
      "Staff+"
    ],
    "description": "Comprehensive deep-dive into System Design at Staff+ FAANG engineering level. Covers the Staff+ design methodology (CIRCLES framework, tradeoff…",
    "sections": [
      "1. System Design Methodology: The Staff+ Approach",
      "2. Design a URL Shortener (bit.ly)",
      "3. Design WhatsApp / Real-Time Chat",
      "4. Design YouTube / Video Streaming Platform",
      "5. Design Twitter / Social Feed"
    ]
  },
  {
    "title": "System Design Fundamentals",
    "category": "System Design",
    "url": "docs.html#sysdesign-fundamentals",
    "tags": [
      "FAANG",
      "system-design",
      "architecture",
      "distributed-systems"
    ],
    "description": "Core concepts for distributed systems design — CAP theorem, consistent hashing, caching strategies, sharding patterns, consensus algorithms, and…",
    "sections": [
      "CAP Theorem — Consistency, Availability, Partition Tolerance",
      "Consistent Hashing — Ring-Based Distribution",
      "Caching Strategies — Eviction, Write Policies, and Architecture",
      "Database Sharding — Horizontal Partitioning Strategies",
      "Consensus Algorithms — Paxos, Raft, Zab, and FLP Impossibility"
    ]
  }
];
