// Auto-generated by scripts/build.mjs — do not edit manually
// Built: 2026-06-23T10:14:45.907Z

window.__BUILD_TIMESTAMP = "2026-06-23T10:14:45.907Z";

window.__ROUTE_MAP = {
  "#aiml-ab-testing-experimentation": "content/aiml/ab-testing-experimentation.json",
  "#aiml-activation-functions": "content/aiml/activation-functions.json",
  "#aiml-ann-history": "content/aiml/ann-history.json",
  "#aiml-cv-deep-dive": "content/aiml/cv-deep-dive.json",
  "#aiml-llm-engineering": "content/aiml/llm-engineering.json",
  "#aiml-ml-behavioral": "content/aiml/ml-behavioral.json",
  "#aiml-ml-chestnut-questions": "content/aiml/ml-chestnut-questions.json",
  "#aiml-ml-coding-patterns": "content/aiml/ml-coding-patterns.json",
  "#aiml-ml-company-focus": "content/aiml/ml-company-focus.json",
  "#aiml-ml-data-centric": "content/aiml/ml-data-centric.json",
  "#aiml-ml-fundamentals": "content/aiml/ml-fundamentals.json",
  "#aiml-ml-gpu-deep-dive": "content/aiml/ml-gpu-deep-dive.json",
  "#aiml-ml-interpretability-fairness": "content/aiml/ml-interpretability-fairness.json",
  "#aiml-ml-leadership-strategy": "content/aiml/ml-leadership-strategy.json",
  "#aiml-ml-math": "content/aiml/ml-math.json",
  "#aiml-ml-mock-interviews": "content/aiml/ml-mock-interviews.json",
  "#aiml-ml-papers": "content/aiml/ml-papers.json",
  "#aiml-ml-production-ops": "content/aiml/ml-production-ops.json",
  "#aiml-ml-project-structure": "content/aiml/ml-project-structure.json",
  "#aiml-ml-roadmap": "content/aiml/ml-roadmap.json",
  "#aiml-ml-staff-system-design": "content/aiml/ml-staff-system-design.json",
  "#aiml-ml-system-design": "content/aiml/ml-system-design.json",
  "#aiml-ml-zero-to-hero": "content/aiml/ml-zero-to-hero.json",
  "#aiml-neural-network-training": "content/aiml/neural-network-training.json",
  "#aiml-nlp-deep-dive": "content/aiml/nlp-deep-dive.json",
  "#aiml-recommendation-systems": "content/aiml/recommendation-systems.json",
  "#aiml-rl-rlhf": "content/aiml/rl-rlhf.json",
  "#aiml-supervised-learning": "content/aiml/supervised-learning.json",
  "#aiml-types-of-anns": "content/aiml/types-of-anns.json",
  "#aiml-unsupervised-learning": "content/aiml/unsupervised-learning.json",
  "#database-fundamentals": "content/databases/databases.json",
  "#faang-facts": "content/faang/faang-facts.json",
  "#genai-alignment": "content/genai/alignment.json",
  "#genai-context-engineering": "content/genai/context-engineering.json",
  "#genai-finetuning": "content/genai/fine-tuning.json",
  "#genai-harness-engineering": "content/genai/harness-engineering.json",
  "#genai-kvcache": "content/genai/kv-cache.json",
  "#genai-llm-serving": "content/genai/llm-serving.json",
  "#genai-loop-engineering": "content/genai/loop-engineering.json",
  "#genai-moe": "content/genai/mixture-of-experts.json",
  "#genai-prompt-engineering": "content/genai/prompt-engineering.json",
  "#genai-rag": "content/genai/rag.json",
  "#genai-pretraining": "content/genai/pretraining.json",
  "#genai-transformer-architecture": "content/genai/transformer-architecture.json",
  "#genai-what-is-llm": "content/genai/what-is-llm.json",
  "#py-algorithms": "content/python/basics/algorithms.json",
  "#py-basics-api": "content/python/basics/api.json",
  "#py-complexity": "content/python/basics/complexity.json",
  "#py-basics-concurrency": "content/python/basics/concurrency.json",
  "#py-basics-datatypes": "content/python/basics/datatypes.json",
  "#py-design-docs": "content/python/basics/design-docs.json",
  "#py-ds-builtins": "content/python/basics/ds-builtins.json",
  "#py-ds-graph": "content/python/basics/ds-graph.json",
  "#py-ds-heap": "content/python/basics/ds-heap.json",
  "#py-ds-linkedlist": "content/python/basics/ds-linkedlist.json",
  "#py-ds-stackqueue": "content/python/basics/ds-stackqueue.json",
  "#py-ds-tree": "content/python/basics/ds-tree.json",
  "#py-exceptions": "content/python/basics/exceptions.json",
  "#py-basics-files": "content/python/basics/files.json",
  "#py-functional": "content/python/basics/functional.json",
  "#py-google-culture": "content/python/basics/google-culture.json",
  "#py-basics-io": "content/python/basics/io.json",
  "#py-logging": "content/python/basics/logging.json",
  "#py-basics-loops": "content/python/basics/loops.json",
  "#py-memory": "content/python/basics/memory.json",
  "#py-modules": "content/python/basics/modules.json",
  "#py-oop": "content/python/basics/oop.json",
  "#py-performance": "content/python/basics/performance.json",
  "#py-security": "content/python/basics/security.json",
  "#py-testing": "content/python/basics/testing.json",
  "#py-typing": "content/python/basics/typing.json",
  "#python-history": "content/python/python-history.json",
  "#sysdesign-fundamentals": "content/sysdesign/system-design.json"
};

window.__SEARCH_INDEX = [
  {
    "title": "Data Types & Operations",
    "category": "Python",
    "url": "docs.html#py-basics-datatypes",
    "tags": [
      "faang",
      "python",
      "data-types"
    ]
  },
  {
    "title": "Loops & Control Flow",
    "category": "Python",
    "url": "docs.html#py-basics-loops",
    "tags": [
      "faang",
      "python",
      "control-flow"
    ]
  },
  {
    "title": "Input &amp; Output",
    "category": "Python",
    "url": "docs.html#py-basics-io",
    "tags": [
      "faang",
      "python",
      "i/o"
    ]
  },
  {
    "title": "File Handling",
    "category": "Python",
    "url": "docs.html#py-basics-files",
    "tags": [
      "faang",
      "python",
      "file-handling"
    ]
  },
  {
    "title": "Time & Space Complexity",
    "category": "Python",
    "url": "docs.html#py-complexity",
    "tags": [
      "faang",
      "python",
      "complexity"
    ]
  },
  {
    "title": "Built-in Collections",
    "category": "Python",
    "url": "docs.html#py-ds-builtins",
    "tags": [
      "faang",
      "python",
      "data-structures"
    ]
  },
  {
    "title": "Linked Lists",
    "category": "Python",
    "url": "docs.html#py-ds-linkedlist",
    "tags": [
      "faang",
      "python",
      "data-structures",
      "linked-list"
    ]
  },
  {
    "title": "Stacks & Queues",
    "category": "Python",
    "url": "docs.html#py-ds-stackqueue",
    "tags": [
      "faang",
      "python",
      "data-structures",
      "stack-queue",
      "staff+",
      "concurrent-queues",
      "ring-buffer"
    ]
  },
  {
    "title": "Priority Queues & Heaps",
    "category": "Python",
    "url": "docs.html#py-ds-heap",
    "tags": [
      "faang",
      "python",
      "data-structures",
      "heap",
      "staff+",
      "fibonacci-heap",
      "priority-queue"
    ]
  },
  {
    "title": "Trees & BSTs",
    "category": "Python",
    "url": "docs.html#py-ds-tree",
    "tags": [
      "faang",
      "python",
      "data-structures",
      "tree",
      "staff+",
      "b-tree",
      "lsm-tree"
    ]
  },
  {
    "title": "Graphs & Networks",
    "category": "Python",
    "url": "docs.html#py-ds-graph",
    "tags": [
      "faang",
      "python",
      "data-structures",
      "graph",
      "staff+",
      "distributed-graph",
      "pregel"
    ]
  },
  {
    "title": "OOP & Design Patterns",
    "category": "Python",
    "url": "docs.html#py-oop",
    "tags": [
      "faang",
      "python",
      "oop",
      "advanced",
      "design-patterns",
      "metaclasses",
      "staff+"
    ]
  },
  {
    "title": "Testing & Mocking",
    "category": "Python",
    "url": "docs.html#py-testing",
    "tags": [
      "faang",
      "python",
      "testing",
      "core-patterns"
    ]
  },
  {
    "title": "Exception Handling",
    "category": "Python",
    "url": "docs.html#py-exceptions",
    "tags": [
      "faang",
      "python",
      "exceptions",
      "core-patterns"
    ]
  },
  {
    "title": "Type Hints & Mypy",
    "category": "Python",
    "url": "docs.html#py-typing",
    "tags": [
      "faang",
      "python",
      "typing",
      "core-patterns"
    ]
  },
  {
    "title": "Memory Management & GC",
    "category": "Python",
    "url": "docs.html#py-memory",
    "tags": [
      "faang",
      "python",
      "memory",
      "core-patterns"
    ]
  },
  {
    "title": "Modules, Packages & Import System",
    "category": "Python",
    "url": "docs.html#py-modules",
    "tags": [
      "faang",
      "python",
      "modules",
      "core-patterns"
    ]
  },
  {
    "title": "Multithreading & Concurrency",
    "category": "Python",
    "url": "docs.html#py-basics-concurrency",
    "tags": [
      "faang",
      "python",
      "concurrency",
      "advanced"
    ]
  },
  {
    "title": "Algorithms & Patterns",
    "category": "Python",
    "url": "docs.html#py-algorithms",
    "tags": [
      "faang",
      "python",
      "algorithms",
      "coding"
    ]
  },
  {
    "title": "API Handling",
    "category": "Python",
    "url": "docs.html#py-basics-api",
    "tags": [
      "faang",
      "python",
      "api"
    ]
  },
  {
    "title": "Functional Programming Patterns",
    "category": "Python",
    "url": "docs.html#py-functional",
    "tags": [
      "faang",
      "python",
      "functional programming",
      "core-patterns"
    ]
  },
  {
    "title": "Performance Optimization",
    "category": "Python",
    "url": "docs.html#py-performance",
    "tags": [
      "faang",
      "python",
      "performance",
      "advanced"
    ]
  },
  {
    "title": "Google Staff Culture — Python Edition",
    "category": "Python",
    "url": "docs.html#py-google-culture",
    "tags": [
      "faang",
      "python",
      "google",
      "staff+",
      "advanced"
    ]
  },
  {
    "title": "Design Docs & Technical Planning",
    "category": "Python",
    "url": "docs.html#py-design-docs",
    "tags": [
      "faang",
      "python",
      "design-docs",
      "staff+",
      "advanced"
    ]
  },
  {
    "title": "Python Security Patterns",
    "category": "Python",
    "url": "docs.html#py-security",
    "tags": [
      "faang",
      "python",
      "security",
      "staff+",
      "advanced"
    ]
  },
  {
    "title": "Logging & Observability",
    "category": "Python",
    "url": "docs.html#py-logging",
    "tags": [
      "faang",
      "python",
      "logging",
      "observability",
      "staff+",
      "advanced"
    ]
  },
  {
    "title": "ML Fundamentals",
    "category": "AI/ML",
    "url": "docs.html#aiml-ml-fundamentals",
    "tags": [
      "faang",
      "core",
      "basics"
    ]
  },
  {
    "title": "Supervised Learning",
    "category": "AI/ML",
    "url": "docs.html#aiml-supervised-learning",
    "tags": [
      "faang",
      "core",
      "supervised"
    ]
  },
  {
    "title": "Unsupervised Learning",
    "category": "AI/ML",
    "url": "docs.html#aiml-unsupervised-learning",
    "tags": [
      "faang",
      "core",
      "unsupervised"
    ]
  },
  {
    "title": "Data-Centric AI",
    "category": "AI/ML",
    "url": "docs.html#aiml-ml-data-centric",
    "tags": [
      "faang",
      "core",
      "data"
    ]
  },
  {
    "title": "ML Math (Probability & Linear Algebra)",
    "category": "AI/ML",
    "url": "docs.html#aiml-ml-math",
    "tags": [
      "faang",
      "core",
      "mathematics"
    ]
  },
  {
    "title": "A/B Testing & Experimentation",
    "category": "AI/ML",
    "url": "docs.html#aiml-ab-testing-experimentation",
    "tags": [
      "faang",
      "core",
      "experimentation"
    ]
  },
  {
    "title": "Activation Functions",
    "category": "AI/ML",
    "url": "docs.html#aiml-activation-functions",
    "tags": [
      "faang",
      "deep-learning",
      "activation"
    ]
  },
  {
    "title": "Neural Network Training",
    "category": "AI/ML",
    "url": "docs.html#aiml-neural-network-training",
    "tags": [
      "faang",
      "deep-learning",
      "training"
    ]
  },
  {
    "title": "Introduction to Neural Networks",
    "category": "AI/ML",
    "url": "docs.html#aiml-ann-history",
    "tags": [
      "faang",
      "deep-learning",
      "history"
    ]
  },
  {
    "title": "Types of Artificial Neural Networks",
    "category": "AI/ML",
    "url": "docs.html#aiml-types-of-anns",
    "tags": [
      "faang",
      "deep-learning",
      "architectures"
    ]
  },
  {
    "title": "ML From Zero to Hero",
    "category": "AI/ML",
    "url": "docs.html#aiml-ml-zero-to-hero",
    "tags": [
      "faang",
      "from-scratch",
      "implementation"
    ]
  },
  {
    "title": "ML Coding Patterns",
    "category": "AI/ML",
    "url": "docs.html#aiml-ml-coding-patterns",
    "tags": [
      "faang",
      "coding",
      "patterns"
    ]
  },
  {
    "title": "ML Research Papers",
    "category": "AI/ML",
    "url": "docs.html#aiml-ml-papers",
    "tags": [
      "faang",
      "research",
      "papers"
    ]
  },
  {
    "title": "ML System Design",
    "category": "AI/ML",
    "url": "docs.html#aiml-ml-system-design",
    "tags": [
      "faang",
      "system-design",
      "architecture"
    ]
  },
  {
    "title": "Recommendation Systems",
    "category": "AI/ML",
    "url": "docs.html#aiml-recommendation-systems",
    "tags": [
      "faang",
      "system-design",
      "recommender"
    ]
  },
  {
    "title": "GPU Deep Dive for ML",
    "category": "AI/ML",
    "url": "docs.html#aiml-ml-gpu-deep-dive",
    "tags": [
      "faang",
      "infrastructure",
      "gpu",
      "performance"
    ]
  },
  {
    "title": "ML Project Structure",
    "category": "AI/ML",
    "url": "docs.html#aiml-ml-project-structure",
    "tags": [
      "faang",
      "system-design",
      "workflow"
    ]
  },
  {
    "title": "ML Behavioral Interview (STAR)",
    "category": "AI/ML",
    "url": "docs.html#aiml-ml-behavioral",
    "tags": [
      "faang",
      "interview",
      "behavioral",
      "star"
    ]
  },
  {
    "title": "FAANG ML Chestnut Questions",
    "category": "AI/ML",
    "url": "docs.html#aiml-ml-chestnut-questions",
    "tags": [
      "faang",
      "interview",
      "q&a",
      "cheat-sheet"
    ]
  },
  {
    "title": "FAANG Company Focus",
    "category": "AI/ML",
    "url": "docs.html#aiml-ml-company-focus",
    "tags": [
      "faang",
      "interview",
      "company-strategy"
    ]
  },
  {
    "title": "NLP Deep Dive",
    "category": "AI/ML",
    "url": "docs.html#aiml-nlp-deep-dive",
    "tags": [
      "faang",
      "advanced",
      "nlp"
    ]
  },
  {
    "title": "Computer Vision Deep Dive",
    "category": "AI/ML",
    "url": "docs.html#aiml-cv-deep-dive",
    "tags": [
      "faang",
      "advanced",
      "computer-vision"
    ]
  },
  {
    "title": "Reinforcement Learning & RLHF",
    "category": "AI/ML",
    "url": "docs.html#aiml-rl-rlhf",
    "tags": [
      "faang",
      "advanced",
      "reinforcement-learning"
    ]
  },
  {
    "title": "LLM Engineering Deep Dive",
    "category": "AI/ML",
    "url": "docs.html#aiml-llm-engineering",
    "tags": [
      "faang",
      "staff+",
      "llm",
      "genai"
    ]
  },
  {
    "title": "Staff+ ML System Design",
    "category": "AI/ML",
    "url": "docs.html#aiml-ml-staff-system-design",
    "tags": [
      "faang",
      "staff+",
      "system-design"
    ]
  },
  {
    "title": "ML Leadership & Strategy for Staff+",
    "category": "AI/ML",
    "url": "docs.html#aiml-ml-leadership-strategy",
    "tags": [
      "faang",
      "staff+",
      "leadership"
    ]
  },
  {
    "title": "Production ML Operations",
    "category": "AI/ML",
    "url": "docs.html#aiml-ml-production-ops",
    "tags": [
      "faang",
      "staff+",
      "mlops"
    ]
  },
  {
    "title": "ML Interpretability & Responsible AI",
    "category": "AI/ML",
    "url": "docs.html#aiml-ml-interpretability-fairness",
    "tags": [
      "faang",
      "staff+",
      "ethics"
    ]
  },
  {
    "title": "ML Mock Interview Walkthroughs",
    "category": "AI/ML",
    "url": "docs.html#aiml-ml-mock-interviews",
    "tags": [
      "faang",
      "interview",
      "mock",
      "rubric"
    ]
  },
  {
    "title": "LLM Architecture",
    "category": "Gen AI",
    "url": "docs.html#genai-what-is-llm",
    "tags": [
      "faang",
      "gen-ai",
      "llm",
      "architecture",
      "foundations"
    ]
  },
  {
    "title": "Transformer Architecture — Attention Is All You Need",
    "category": "Gen AI",
    "url": "docs.html#genai-transformer-architecture",
    "tags": [
      "faang",
      "gen-ai",
      "transformer",
      "attention",
      "foundations"
    ]
  },
  {
    "title": "Inference Optimization",
    "category": "Gen AI",
    "url": "docs.html#genai-kvcache",
    "tags": [
      "faang",
      "gen-ai",
      "llm",
      "performance",
      "inference"
    ]
  },
  {
    "title": "RAG — Retrieval-Augmented Generation",
    "category": "Gen AI",
    "url": "docs.html#genai-rag",
    "tags": [
      "faang",
      "gen-ai",
      "rag",
      "retrieval",
      "nlp"
    ]
  },
  {
    "title": "Fine-Tuning & PEFT",
    "category": "Gen AI",
    "url": "docs.html#genai-finetuning",
    "tags": [
      "faang",
      "gen-ai",
      "fine-tuning",
      "peft",
      "training"
    ]
  },
  {
    "title": "Prompt Engineering — Techniques & Strategy",
    "category": "Gen AI",
    "url": "docs.html#genai-prompt-engineering",
    "tags": [
      "faang",
      "gen-ai",
      "prompt-engineering",
      "nlp"
    ]
  },
  {
    "title": "Long-Context & Prompt Caching",
    "category": "Gen AI",
    "url": "docs.html#genai-context-engineering",
    "tags": [
      "faang",
      "gen-ai",
      "long-context",
      "prompt-caching",
      "nlp"
    ]
  },
  {
    "title": "LLM Evaluation — Benchmarks & Automated Evals",
    "category": "Gen AI",
    "url": "docs.html#genai-harness-engineering",
    "tags": [
      "faang",
      "gen-ai",
      "llm-evaluation",
      "benchmarks",
      "testing"
    ]
  },
  {
    "title": "LLM Agents — ReAct, Tool Use & Reasoning",
    "category": "Gen AI",
    "url": "docs.html#genai-loop-engineering",
    "tags": [
      "faang",
      "gen-ai",
      "llm-agents",
      "agent",
      "reasoning"
    ]
  },
  {
    "title": "Mixture of Experts — MoE Architecture",
    "category": "Gen AI",
    "url": "docs.html#genai-moe",
    "tags": [
      "faang",
      "gen-ai",
      "moe",
      "architecture",
      "performance"
    ]
  },
  {
    "title": "LLM Serving — Production Inference at Scale",
    "category": "Gen AI",
    "url": "docs.html#genai-llm-serving",
    "tags": [
      "faang",
      "gen-ai",
      "llm-serving",
      "deployment",
      "infrastructure"
    ]
  },
  {
    "title": "Pre-Training LLMs at Scale",
    "category": "Gen AI",
    "url": "docs.html#genai-pretraining",
    "tags": [
      "faang",
      "gen-ai",
      "llm",
      "training",
      "distributed"
    ]
  },
  {
    "title": "Alignment — RLHF, DPO & Safety",
    "category": "Gen AI",
    "url": "docs.html#genai-alignment",
    "tags": [
      "faang",
      "gen-ai",
      "llm",
      "alignment",
      "safety"
    ]
  },
  {
    "title": "System Design Fundamentals",
    "category": "System Design",
    "url": "docs.html#sysdesign-fundamentals",
    "tags": [
      "faang",
      "system-design",
      "architecture",
      "distributed-systems"
    ]
  },
  {
    "title": "Database Fundamentals",
    "category": "Databases",
    "url": "docs.html#database-fundamentals",
    "tags": [
      "faang",
      "databases",
      "storage",
      "infrastructure"
    ]
  },
  {
    "title": "FAANG Engineering Facts",
    "category": "FAANG",
    "url": "docs.html#faang-facts",
    "tags": [
      "faang",
      "interview",
      "company-strategy",
      "reference"
    ]
  },
  {
    "title": "ML Study Roadmap",
    "category": "AI/ML",
    "url": "docs.html#aiml-ml-roadmap",
    "tags": [
      "faang",
      "study-plan",
      "curriculum"
    ]
  },
  {
    "title": "Built-in Collections (legacy route)",
    "category": "Python",
    "url": "docs.html#py-ds-builtins",
    "tags": [
      "python",
      "data",
      "structures",
      "builtins",
      "ds-route"
    ]
  },
  {
    "title": "History of Python",
    "category": "Python",
    "url": "docs.html#python-history",
    "tags": [
      "python",
      "history",
      "guido",
      "van",
      "rossum",
      "timeline",
      "evolution"
    ]
  }
];
