// Dynamic Content Loader for ai bytes Documentation Portal
// Route map generated by scripts/build.mjs — uses window.__ROUTE_MAP

let scrollSpyCleanup = null;

const _routeMap = window.__ROUTE_MAP || {};

// ponytail: hash-based tag colors — no palette maintenance needed
var _TAG_COLORS = ['#4585e8','#34d399','#fbbf24','#c4b5fd','#fb923c','#6366f1','#0ea5e9','#ef4444','#a855f7','#10b981','#f59e0b','#ec4899','#f97316','#d946ef','#22c55e','#eab308','#7c3aed','#2dd4bf'];
function colorizeTags(root) {
  (root || document).querySelectorAll('[data-tag]').forEach(function(el) {
    var t = el.getAttribute('data-tag');
    var h = 0; for (var i = 0; i < t.length; i++) h = ((h << 5) - h) + t.charCodeAt(i);
    var c = _TAG_COLORS[Math.abs(h) % _TAG_COLORS.length];
    el.style.setProperty('--tag-color', c);
    el.style.setProperty('--tag-bg', c + '1A');
    if (document.documentElement.classList.contains('dark')) {
      el.style.setProperty('--tag-bg', c + '2E');
    }
  });
}

async function fetchWithCache(path) {
  var cacheKey = 'ab:' + path;
  try {
    var cached = sessionStorage.getItem(cacheKey);
    if (cached) {
      var parsed = JSON.parse(cached);
      if (parsed && typeof parsed === 'object') return parsed;
    }
  } catch (e) {}
  var res = await fetch(path);
  if (!res.ok) throw new Error('Failed to fetch content');
  var data = await res.json();
  try { sessionStorage.setItem(cacheKey, JSON.stringify(data)); } catch (e) {}
  return data;
}

const COPY_BTN = '<button onclick="copyCode(this)" class="absolute right-3 top-3 opacity-0 group-hover:opacity-100 bg-white dark:bg-slate-900 hover:bg-slate-100 dark:hover:bg-slate-800 border border-slate-200 dark:border-slate-800 px-2.5 py-1.5 rounded-lg text-xs font-sans text-slate-500 transition-all flex items-center gap-1.5"><span class="material-symbols-outlined text-sm" aria-hidden="true">content_copy</span> Copy</button>';

function codeBlock(code, langClass) {
  return `<div class="border border-slate-200 dark:border-slate-800 bg-slate-50 dark:bg-slate-800/40 rounded-xl p-5 text-sm leading-relaxed overflow-x-auto relative group">${COPY_BTN}<pre><code class="${langClass}">${escapeHtml(code)}</code></pre></div>`;
}

function renderSections(sections, dataId, langClass, extraClass) {
  if (!sections) return '';
  return `<div class="flex flex-col gap-8${extraClass || ''}">` + sections.map(function(section, idx) {
    let sectionId = 'section-' + dataId + '-' + idx;
    let refClass = '';
    if (section.title.indexOf('References') !== -1) {
      refClass = ' references-section';
    }
    let sectionLangClass = section.language ? 'language-' + section.language : langClass;
    return (
      '<div id="' + sectionId + '" class="scroll-mt-24 flex flex-col gap-3' + refClass + '">' +
      '<h3 class="text-xl font-semibold text-slate-900 dark:text-white">' + section.title + '</h3>' +
      (section.description ? '<div class="text-slate-600 dark:text-slate-400 text-sm leading-relaxed">' + section.description + '</div>' : '') +
      (section.codeBlock ? codeBlock(section.codeBlock, sectionLangClass) : '') +
      '</div>'
    );
  }).join('\n') + '</div>';
}

async function loadContent(hash) {
  if (scrollSpyCleanup) {
    scrollSpyCleanup();
    scrollSpyCleanup = null;
  }
  const path = _routeMap[hash] || _routeMap['#python-history'];
  const contentArea = document.getElementById('docs-dynamic-content');
  if (!contentArea) return;

  // Show loading state
  contentArea.innerHTML = `
    <div class="animate-pulse space-y-6">
      <div class="h-8 bg-slate-200 dark:bg-slate-800 rounded w-3/4"></div>
      <div class="h-4 bg-slate-200 dark:bg-slate-800 rounded w-1/2"></div>
      <div class="h-40 bg-slate-200 dark:bg-slate-800 rounded"></div>
      <div class="h-4 bg-slate-200 dark:bg-slate-800 rounded w-5/6"></div>
    </div>
  `;

  if (hash === '#readme') {
    try {
      const res = await fetch('README.md');
      const md = await res.text();

      const existing = document.getElementById('readme-modal');
      if (existing) existing.remove();

      const modal = document.createElement('div');
      modal.id = 'readme-modal';
      modal.className = 'fixed inset-0 z-50 flex items-start justify-center pt-12 sm:pt-20 px-4';
      modal.innerHTML =
        '<div class="fixed inset-0 bg-black/30 dark:bg-black/50 backdrop-blur-sm" id="readme-modal-backdrop"></div>' +
        '<div class="relative z-10 w-full max-w-3xl max-h-[80vh] bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl shadow-2xl overflow-hidden flex flex-col">' +
          '<div class="flex items-center justify-between px-6 py-4 border-b border-slate-200 dark:border-slate-800 shrink-0">' +
            '<h2 class="text-sm font-bold text-slate-900 dark:text-white font-sans">README — ai bytes</h2>' +
            '<button id="readme-modal-close" class="w-7 h-7 rounded-lg hover:bg-slate-100 dark:hover:bg-white/5 flex items-center justify-center text-slate-400 hover:text-slate-600 dark:hover:text-slate-300 transition-all" aria-label="Close README">' +
              '<span class="material-symbols-outlined text-[18px]">close</span>' +
            '</button>' +
          '</div>' +
          '<div class="flex-1 overflow-y-auto px-6 py-5 readme-content min-h-0">' + marked.parse(md) + '</div>' +
        '</div>';

      document.body.appendChild(modal);

      if (typeof Prism !== 'undefined') {
        Prism.highlightAllUnder(modal);
      }

      function closeReadme() {
        modal.remove();
        window.location.hash = '#python-history';
      }

      document.getElementById('readme-modal-close').addEventListener('click', closeReadme);
      document.getElementById('readme-modal-backdrop').addEventListener('click', closeReadme);
      document.addEventListener('keydown', function handler(e) {
        if (e.key === 'Escape' && document.getElementById('readme-modal')) {
          closeReadme();
          document.removeEventListener('keydown', handler);
        }
      });
    } catch (e) {
      contentArea.innerHTML = '<p class="text-red-500 dark:text-red-400">Failed to load README.md</p>';
    }
    return;
  }

  const left = document.getElementById('left-sidebar');
  const outline = document.getElementById('docs-right-outline');
  if (left) left.style.display = '';
  if (outline) outline.parentElement.style.display = '';
  const mainEl = document.querySelector('main');
  if (mainEl) {
    mainEl.classList.remove('max-w-4xl');
    mainEl.classList.add('max-w-3xl');
  }

  try {
    const data = await fetchWithCache(path);

    // Render content dynamically
    const langClass = data.language ? 'language-' + data.language : 'text-slate-800 dark:text-slate-200';
    let embedCode = '';
    const isInteractive = data.interactive === true;
    if (isInteractive) {
      embedCode = `
        <div class="w-full aspect-auto h-[530px] md:aspect-[16/12] md:h-auto border border-blue-200 dark:border-gray-700 rounded-2xl overflow-hidden shadow-lg bg-white dark:bg-[#0F1115]">
          <iframe src="${data.id}.html" class="w-full h-full border-none" allowfullscreen aria-label="${data.title || 'Interactive visualization'}"></iframe>
        </div>
      `;
      if (data.sections) {
        embedCode += renderSections(data.sections, data.id, langClass, ' mt-8');
      } else if (data.codeBlock) {
        embedCode += `
          <div class="mt-6 text-xs font-mono font-bold uppercase tracking-wider text-slate-400 dark:text-slate-500 mb-2">Sample Code / Syntax</div>
          <div id="section-syntax" class="scroll-mt-24">${codeBlock(data.codeBlock, langClass)}</div>
        `;
      }
    } else if (data.sections) {
      embedCode = renderSections(data.sections, data.id, langClass, '');
    } else if (data.timeline) {
      let items = '';
      for (let ti = 0; ti < data.timeline.length; ti++) {
        const t = data.timeline[ti];
        const delay = ti * 80;
        items += `
          <div class="timeline-entry" style="animation-delay: ${delay}ms">
            <div class="timeline-dot">
              <span class="timeline-dot-year">${t.year}</span>
              <span class="timeline-dot-ring"></span>
            </div>
            <div class="timeline-body">
              <div class="flex items-center gap-2 mb-1">
                <h4 class="timeline-title">${t.title || ''}</h4>
                <span class="timeline-tag">${t.tag || 'Release'}</span>
              </div>
              <p class="timeline-event">${t.event}</p>
            </div>
          </div>
        `;
      }
      embedCode = `
        <div id="section-syntax" class="scroll-mt-24 mt-4">
          <div class="timeline-track">${items}</div>
        </div>
      `;
      if (data.codeBlock) {
        embedCode += `<div class="mt-6">${codeBlock(data.codeBlock, langClass)}</div>`;
      }
    } else {
      embedCode = `<div id="section-syntax" class="scroll-mt-24">${data.codeBlock ? codeBlock(data.codeBlock, langClass) : ''}</div>`;
    }

    contentArea.innerHTML = `
      <article class="flex flex-col gap-5 docs-section" role="region" aria-label="${data.title || 'Documentation content'}">
        <div class="flex flex-col gap-3">
          <!-- Premium Minimalist Breadcrumbs -->
          <nav class="flex items-center gap-1.5 text-[10px] font-bold text-slate-400 dark:text-slate-500 uppercase tracking-wider select-none">
            <span>${data.category}</span>
            <span class="material-symbols-outlined text-[12px] text-slate-300 dark:text-slate-700">chevron_right</span>
            <span class="text-brand-500">${data.subcategory}</span>
          </nav>
          
          <!-- Document Title -->
          <h1 class="text-3xl sm:text-4xl font-bold text-slate-900 dark:text-white tracking-tight">${data.title}</h1>
          
          <!-- Tags List -->
          ${data.tags && data.tags.length > 0 ? `
            <div class="flex flex-wrap gap-1.5 mt-0.5">
              ${data.tags.map(function(t) {
                return '<span class="inline-flex items-center px-2.5 py-0.5 rounded-full text-[10px] font-semibold uppercase tracking-wider tag-badge cursor-default" data-tag="' + t + '">' + t + '</span>';
              }).join('')}
            </div>
          ` : ''}
        </div>

        <p class="text-slate-600 dark:text-slate-400 leading-relaxed text-base">${data.description}</p>
        
        ${embedCode}

        ${data.comparisonTable ? `
          <div id="section-comparison" class="scroll-mt-24">
            <h4 class="text-xs font-mono font-bold uppercase tracking-wider text-orange-600 dark:text-orange-400 mb-3 mt-6">${data.comparisonTableTitle || 'Comparison Matrix'}</h4>
            <div class="overflow-x-auto border border-slate-200 dark:border-slate-800 rounded-xl bg-white dark:bg-[#0E1115]">
              <table class="w-full text-xs text-left border-collapse">
                <thead class="bg-slate-50 dark:bg-slate-900/60 font-bold font-mono border-b border-slate-200 dark:border-slate-800">
                  <tr>
                    <th class="p-3 text-slate-700 dark:text-slate-200">Model</th>
                    <th class="p-3 text-slate-700 dark:text-slate-200">Execution Paradigm</th>
                    <th class="p-3 text-slate-700 dark:text-slate-200">GIL Restriction</th>
                    <th class="p-3 text-slate-700 dark:text-slate-200">Memory Overhead</th>
                    <th class="p-3 text-slate-700 dark:text-slate-200">Best Suitability</th>
                  </tr>
                </thead>
                <tbody class="font-mono divide-y divide-slate-100 dark:divide-slate-800/60">
                  ${data.comparisonTable.map(row => `
                    <tr class="hover:bg-slate-50/50 dark:hover:bg-slate-900/20">
                      <td class="p-3 font-semibold ${row.colorClass || 'text-slate-800 dark:text-slate-200'}">${row.model}</td>
                      <td class="p-3">${row.paradigm}</td>
                      <td class="p-3 ${row.gilColorClass || ''}">${row.gil}</td>
                      <td class="p-3">${row.memory}</td>
                      <td class="p-3">${row.suitability}</td>
                    </tr>
                  `).join('')}
                </tbody>
              </table>
            </div>
          </div>
        ` : ''}

        ${data.diffTable ? `
          <div id="section-differences" class="scroll-mt-24">
            <h4 class="text-xs font-mono font-bold uppercase tracking-wider text-orange-600 dark:text-orange-400 mb-3 mt-6">Differences: Multithreading vs Concurrency</h4>
            <div class="overflow-x-auto border border-slate-200 dark:border-slate-800 rounded-xl bg-white dark:bg-[#0E1115]">
              <table class="w-full text-xs text-left border-collapse table-fixed">
                <thead class="bg-slate-50 dark:bg-slate-900/60 font-bold font-mono border-b border-slate-200 dark:border-slate-800">
                  <tr>
                    <th class="p-3 text-slate-700 dark:text-slate-200 w-[20%] align-top">Dimension</th>
                    <th class="p-3 text-slate-700 dark:text-slate-200 w-[40%] align-top">Concurrency</th>
                    <th class="p-3 text-slate-700 dark:text-slate-200 w-[40%] align-top">Multithreading</th>
                  </tr>
                </thead>
                <tbody class="divide-y divide-slate-100 dark:divide-slate-800/60">
                  ${data.diffTable.map(row => `
                    <tr class="hover:bg-slate-50/50 dark:hover:bg-slate-900/20">
                      <td class="p-3 font-mono font-semibold text-orange-600 dark:text-orange-400 align-top">${row.dimension}</td>
                      <td class="p-3 text-slate-600 dark:text-slate-300 text-xs align-top leading-relaxed">${row.concurrency}</td>
                      <td class="p-3 text-slate-600 dark:text-slate-300 text-xs align-top leading-relaxed">${row.multithreading}</td>
                    </tr>
                  `).join('')}
                </tbody>
              </table>
            </div>
          </div>
        ` : ''}
        ${data.details ? `
        <div id="section-dive" class="scroll-mt-24 p-5 rounded-xl text-sm leading-relaxed deep-dive-box">
          <div>
            <h4 class="font-bold text-slate-900 dark:text-white mb-1">Deep Dive</h4>
            ${data.details}
          </div>
        </div>
        ` : ''}
      </article>
    `;

    colorizeTags(contentArea);

    // Highlight active link and its parent section in left sidebar
    document.querySelectorAll('.sidebar-section').forEach(function(section) {
      section.classList.remove('section-active');
    });
    document.querySelectorAll('.sidebar-link').forEach(link => {
      if (link.getAttribute('href') === hash) {
        link.classList.add('active-doc-link');
        link.setAttribute('aria-current', 'page');
        var section = link.closest('.sidebar-section');
        if (section) section.classList.add('section-active');
      } else {
        link.classList.remove('active-doc-link');
        link.removeAttribute('aria-current');
      }
    });

    // Populate right outline dynamically
    const outlineArea = document.getElementById('docs-right-outline');
    if (outlineArea) {
      if (data.sections) {
        let outlineHtml = data.sections.map((section, idx) => {
          const sectionId = `section-${data.id}-${idx}`;
          return `<a href="#${sectionId}" class="outline-link">${section.title}</a>`;
        }).join('\n');
        if (data.comparisonTable) {
          outlineHtml += `\n<a href="#section-comparison" class="outline-link">Comparison Matrix</a>`;
        }
        if (data.diffTable) {
          outlineHtml += `\n<a href="#section-differences" class="outline-link">Differences Matrix</a>`;
        }
        if (data.details) {
          outlineHtml += `\n<a href="#section-dive" class="outline-link">Deep Dive</a>`;
        }
        outlineArea.innerHTML = outlineHtml;
      } else {
        const syntaxLabel = data.id === 'python-history' ? 'Timeline' : 'Syntax Guide';
        let outlineHtml = `<a href="#section-syntax" class="outline-link">${syntaxLabel}</a>`;
        if (data.comparisonTable) {
          outlineHtml += `\n<a href="#section-comparison" class="outline-link">Comparison Matrix</a>`;
        }
        if (data.diffTable) {
          outlineHtml += `\n<a href="#section-differences" class="outline-link">Differences Matrix</a>`;
        }
        if (data.details) {
          outlineHtml += `\n<a href="#section-dive" class="outline-link">Deep Dive</a>`;
        }
        outlineArea.innerHTML = outlineHtml;
      }
      setupOutlineSmoothScroll();
      scrollSpyCleanup = setupOutlineScrollSpy();
    }

    if (contentArea.querySelector('pre code')) {
      if (typeof Prism !== 'undefined') {
        Prism.highlightAllUnder(contentArea);
      }
    }

    // Trigger entrance animations
    requestAnimationFrame(function() {
      requestAnimationFrame(function() {
        const section = contentArea.querySelector('article');
        if (section) section.classList.add('anim-ready');
        if (data.sections) {
          data.sections.forEach((_, idx) => {
            const sec = document.getElementById(`section-${data.id}-${idx}`);
            if (sec) sec.classList.add('anim-ready');
          });
        }
        const syntax = document.getElementById('section-syntax');
        if (syntax) syntax.classList.add('anim-ready');
        const dive = document.getElementById('section-dive');
        if (dive) {
          if (dive.getBoundingClientRect().top < window.innerHeight) {
            dive.classList.add('anim-ready');
          } else {
            const obs = new IntersectionObserver(function(entries) {
              entries.forEach(function(entry) {
                if (entry.isIntersecting) {
                  entry.target.classList.add('anim-ready');
                  obs.unobserve(entry.target);
                }
              });
            }, { threshold: 0.15 });
            obs.observe(dive);
          }
        }
      });
    });

  } catch (error) {
    console.error("Error in loadContent:", error);
    contentArea.innerHTML = `
      <div class="p-6 border-2 border-red-200 dark:border-red-900/30 bg-red-50 dark:bg-red-950/10 rounded-xl text-red-600 dark:text-red-400 text-sm">
        <h3 class="font-bold mb-1">Error Loading Document</h3>
        <p>Failed to load the requested study guide from path: ${path}. Error: ${error.message}</p>
      </div>
    `;
  }
}

function setupOutlineSmoothScroll() {
  const outline = document.getElementById('docs-right-outline');
  if (!outline) return;
  outline.addEventListener('click', function(e) {
    const link = e.target.closest('.outline-link');
    if (!link) return;
    const targetId = link.getAttribute('href');
    const targetElement = document.querySelector(targetId);
    if (targetElement) {
      e.preventDefault();
      targetElement.scrollIntoView({ behavior: 'smooth', block: 'start' });
      document.querySelectorAll('.outline-link').forEach(l => {
        l.classList.toggle('active-outline', l.getAttribute('href') === targetId);
      });
    }
  });
}

function setupOutlineScrollSpy() {
  const links = document.querySelectorAll('.outline-link');
  if (links.length === 0) return null;

  const sections = Array.from(links).map(link => {
    return document.querySelector(link.getAttribute('href'));
  }).filter(Boolean);

  if (sections.length === 0) return null;

  function updateActiveLink() {
    const scrollPosition = window.scrollY + 120;
    
    if ((window.innerHeight + window.scrollY) >= document.documentElement.scrollHeight - 50) {
      links.forEach((link, idx) => link.classList.toggle('active-outline', idx === links.length - 1));
      return;
    }

    let activeSection = null;
    for (let i = 0; i < sections.length; i++) {
      const section = sections[i];
      if (section.offsetTop <= scrollPosition) {
        activeSection = section;
      } else {
        break;
      }
    }

    if (!activeSection && sections.length > 0) {
      activeSection = sections[0];
    }

    if (activeSection) {
      const activeId = activeSection.getAttribute('id');
      links.forEach(link => link.classList.toggle('active-outline', link.getAttribute('href') === `#${activeId}`));
    }
  }

  let tick = false;
  const onScroll = () => {
    if (!tick) {
      requestAnimationFrame(() => {
        updateActiveLink();
        tick = false;
      });
      tick = true;
    }
  };

  window.addEventListener('scroll', onScroll, { passive: true });
  updateActiveLink();

  return () => {
    window.removeEventListener('scroll', onScroll);
  };
}

function escapeHtml(text) {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}

function showToast(message) {
  const existingToast = document.getElementById('clipboard-toast');
  if (existingToast) {
    existingToast.remove();
  }

  const toast = document.createElement('div');
  toast.id = 'clipboard-toast';
  toast.className = 'fixed bottom-6 right-6 z-50 flex items-center gap-2.5 bg-slate-900/90 dark:bg-slate-800/90 backdrop-blur-md text-white border border-slate-700/50 px-4 py-2.5 rounded-xl shadow-xl text-sm font-sans font-medium transition-all duration-300 transform translate-y-10 opacity-0';
  toast.innerHTML = `
    <span class="material-symbols-outlined text-[18px] text-emerald-400" aria-hidden="true">check_circle</span>
    <span>${message}</span>
  `;

  document.body.appendChild(toast);

  requestAnimationFrame(function() {
    toast.classList.remove('translate-y-10', 'opacity-0');
    toast.classList.add('translate-y-0', 'opacity-100');
  });

  setTimeout(function() {
    toast.classList.remove('translate-y-0', 'opacity-100');
    toast.classList.add('translate-y-10', 'opacity-0');
    setTimeout(function() {
      toast.remove();
    }, 300);
  }, 2200);
}

function copyCode(btn) {
  const codeEl = btn.parentElement.querySelector('code');
  if (!codeEl) return;
  navigator.clipboard.writeText(codeEl.textContent).then(function() {
    const originalHTML = btn.innerHTML;
    btn.innerHTML = '<span class="material-symbols-outlined text-sm text-emerald-500">check</span> Copied!';
    btn.disabled = true;
    showToast('Code copied to clipboard!');
    setTimeout(function() {
      btn.innerHTML = originalHTML;
      btn.disabled = false;
    }, 2000);
  }).catch(function(err) {
    console.error('Failed to copy: ', err);
  });
}
window.copyCode = copyCode;
window.addEventListener('DOMContentLoaded', () => {
  const initialHash = window.location.hash || '#python-history';
  loadContent(initialHash);
});

window.addEventListener('hashchange', () => {
  loadContent(window.location.hash);
  window.scrollTo({ top: 0, behavior: 'smooth' });
});

window.addEventListener('theme-changed', () => {
  colorizeTags();
});
