// scripts/build.mjs
// Regenerates js/generated.js from content/ JSON files

import fs from 'fs';
import path from 'path';

const contentDir = 'content';
const outputFile = 'js/generated.js';

function stripHtml(html) {
  return html
    .replace(/<[^>]*>/g, '')
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#039;/g, "'")
    .replace(/&nbsp;/g, ' ')
    .trim();
}

function truncate(text, max = 150) {
  if (!text) return '';
  if (text.length <= max) return text;
  return text.slice(0, max).replace(/\s+\S*$/, '') + '…';
}

function generateHashFromId(id) {
  return '#' + id;
}

function scanContent() {
  const routes = {};
  const searchIndex = [];

  function processDir(dir) {
    const entries = fs.readdirSync(dir, { withFileTypes: true });
    for (const entry of entries) {
      const fullPath = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        processDir(fullPath);
      } else if (entry.name.endsWith('.json')) {
        try {
          const data = JSON.parse(fs.readFileSync(fullPath, 'utf8'));
          const id = data.id;
          if (!id) continue;

          const relativePath = path.join(dir, entry.name).replace(/\\/g, '/');
          const hash = generateHashFromId(id);
          routes[hash] = relativePath;

          // Build search entry
          const plainDesc = truncate(stripHtml(data.description || ''), 150);
          const sectionTitles = (data.sections || []).slice(0, 5).map(s => s.title);
          const searchEntry = {
            title: data.title || id,
            category: data.category || '',
            url: `docs.html${hash}`,
            tags: data.tags || [],
            description: plainDesc,
            sections: sectionTitles
          };
          searchIndex.push(searchEntry);
        } catch (e) {
          console.error(`Skipping ${fullPath}: ${e.message}`);
        }
      }
    }
  }

  if (fs.existsSync(contentDir)) {
    processDir(contentDir);
  }

  return { routes, searchIndex };
}

function generateJs(routes, searchIndex) {
  const timestamp = new Date().toISOString();
  const routeMapLines = Object.entries(routes)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([hash, filePath]) => `  "${hash}": "${filePath}",`)
    .join('\n');

  const searchIndexLines = searchIndex
    .map(entry => {
      const entryJson = JSON.stringify(entry, null, 2);
      return '  ' + entryJson.split('\n').join('\n  ');
    })
    .join(',\n');

  return `// Auto-generated by scripts/build.mjs — do not edit manually
// Built: ${timestamp}

window.__BUILD_TIMESTAMP = "${timestamp}";

window.__ROUTE_MAP = {
${routeMapLines}
};

window.__SEARCH_INDEX = [
${searchIndexLines}
];
`;
}

function main() {
  console.log('Rebuilding js/generated.js from content/...');
  const { routes, searchIndex } = scanContent();
  const js = generateJs(routes, searchIndex);
  fs.writeFileSync(outputFile, js);
  console.log(`Wrote ${outputFile} (${Object.keys(routes).length} routes, ${searchIndex.length} search entries)`);
}

main();
