// scripts/build.mjs
// Regenerates js/generated.js from content/ JSON files

import fs from 'fs';
import path from 'path';

const contentDir = 'content';
const outputFile = 'js/generated.js';

function stripHtml(html) {
  return html
    .replace(/<[^>]*>/g, '')
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#039;/g, "'")
    .replace(/&nbsp;/g, ' ')
    .trim();
}

function truncate(text, max = 150) {
  if (!text) return '';
  if (text.length <= max) return text;
  return text.slice(0, max).replace(/\s+\S*$/, '') + '…';
}

function generateHashFromId(id) {
  return '#' + id;
}

function scanContent() {
  const routes = {};
  const searchIndex = [];

  function processDir(dir) {
    const entries = fs.readdirSync(dir, { withFileTypes: true });
    for (const entry of entries) {
      const fullPath = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        processDir(fullPath);
      } else if (entry.name.endsWith('.json')) {
        try {
          const data = JSON.parse(fs.readFileSync(fullPath, 'utf8'));
          const id = data.id;
          if (!id) continue;

          const relativePath = path.join(dir, entry.name).replace(/\\/g, '/');
          const hash = generateHashFromId(id);
          routes[hash] = relativePath;

          // Build search entry
          const plainDesc = truncate(stripHtml(data.description || ''), 150);
          const sectionTitles = (data.sections || []).map(s => s.title);
          const searchEntry = {
            title: data.title || id,
            category: data.category || '',
            url: `docs.html${hash}`,
            tags: data.tags || [],
            description: plainDesc,
            sections: sectionTitles
          };
          searchIndex.push(searchEntry);
        } catch (e) {
          console.error(`Skipping ${fullPath}: ${e.message}`);
        }
      }
    }
  }

  if (fs.existsSync(contentDir)) {
    processDir(contentDir);
  }

  return { routes, searchIndex };
}

function generateJs(routes, searchIndex) {
  const timestamp = new Date().toISOString();
  const routeMapLines = Object.entries(routes)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([hash, filePath]) => `  "${hash}": "${filePath}",`)
    .join('\n');

  const searchIndexLines = searchIndex
    .map(entry => {
      const entryJson = JSON.stringify(entry, null, 2);
      return '  ' + entryJson.split('\n').join('\n  ');
    })
    .join(',\n');

  return `// Auto-generated by scripts/build.mjs — do not edit manually
// Built: ${timestamp}

window.__BUILD_TIMESTAMP = "${timestamp}";

window.__ROUTE_MAP = {
${routeMapLines}
};

window.__SEARCH_INDEX = [
${searchIndexLines}
];
`;
}

function generateSitemap(searchIndex) {
  const timestamp = new Date().toISOString().split('T')[0];
  const baseUrl = 'https://kallolchakraborty.github.io/ai-bytes/';

  let xml = `<?xml version="1.0" encoding="UTF-8"?>\n`;
  xml += `<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n`;

  // Root landing page
  xml += `  <url>\n`;
  xml += `    <loc>${baseUrl}index.html</loc>\n`;
  xml += `    <lastmod>${timestamp}</lastmod>\n`;
  xml += `    <changefreq>daily</changefreq>\n`;
  xml += `    <priority>1.0</priority>\n`;
  xml += `  </url>\n`;

  // Docs landing page
  xml += `  <url>\n`;
  xml += `    <loc>${baseUrl}docs.html</loc>\n`;
  xml += `    <lastmod>${timestamp}</lastmod>\n`;
  xml += `    <changefreq>daily</changefreq>\n`;
  xml += `    <priority>0.9</priority>\n`;
  xml += `  </url>\n`;

  // Hash dynamic pages
  for (const entry of searchIndex) {
    // entry.url is like "docs.html#hash"
    const hash = entry.url.substring(entry.url.indexOf('#'));
    const priority = (entry.category === 'Gen AI' || entry.category === 'AI/ML') ? '0.8' : '0.6';

    xml += `  <url>\n`;
    xml += `    <loc>${baseUrl}docs.html${hash}</loc>\n`;
    xml += `    <lastmod>${timestamp}</lastmod>\n`;
    xml += `    <changefreq>weekly</changefreq>\n`;
    xml += `    <priority>${priority}</priority>\n`;
    xml += `  </url>\n`;
  }

  xml += `</urlset>\n`;
  fs.writeFileSync('sitemap.xml', xml);
  console.log(`Wrote sitemap.xml containing ${searchIndex.length + 2} URLs.`);
}

function main() {
  console.log('Rebuilding js/generated.js from content/...');
  const { routes, searchIndex } = scanContent();
  const js = generateJs(routes, searchIndex);
  fs.writeFileSync(outputFile, js);
  console.log(`Wrote ${outputFile} (${Object.keys(routes).length} routes, ${searchIndex.length} search entries)`);
  generateSitemap(searchIndex);
}

main();
